### ISSUE TITLE
tlsio_schannel.c issues using IoTHubClient AMQP Sample

### ISSUE THREAD

**Issue by henrikdimander** [Azure/azure-c-shared-utility#10]
When running the IoTHubClient SDK sample for AMQP
_azure-iot-sdks/c/iothub_client/samples/iothub_client_sample_amqp/windows/_ 
with latest SDK version **1.0.7** on a Windows 10 PC, I get the following error:

_Error: Time:Thu May 19 00:03:14 2016 File:C:\repos\azure-iot-gateway-sdk\deps\azure-c-shared-utility\src\tlsio_schannel.c Func:_on_underlying_io_bytes_received Line:395 [0x80090308]_

The error is generated in the file due to the status value -2146893048 received from the function InitializeSecurityContext in sspi.c class.

The status -2146893048 refers to SEC_E_INVALID_TOKEN error code.

Any idea why this error is occuring?

**Update 20-May:** 
This is working using version v1.0.5 of the SDK, but seem broken from v1.0.6 

Thanks
/Henrik

**Comment by anhashia** [comment]
Investigating this.

**Comment by anhashia** [comment]
Unable to reproduce the issue with latest sample  c\iothub_client\samples\iothub_client_sample_amqp\windows on **master**. Able to successfully send and receive message using Device Explorer for testing.

**Comment by anhashia** [comment]
Closing. Please re-activate if you still are having issues. Thanks !
