### ISSUE TITLE
HTTPAPI_SetOption missing proxy option on Windows implementation

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-c-shared-utility#103]
Hi,

I'm facing an issue using the HTTP API.
I need to use the SetOption method to configure a proxy :

`httpapi_res = HTTPAPI_SetOption(http_handle, OPTION_HTTP_PROXY, (void*)&proxy);`

This code works on Linux but not on Windows, the option seems not to be handled in the httpapi_winhttp.c implementation:

`unknown option proxy_data`

Thanks.

**Comment by tameraw** [comment]
@alexmrtn - That's correct. Currently this option is not supported in the SDK on Windows. However, you should be able to specify the proxy settings in the OS directly and should get picked up by the SDK.

**Comment by alexmrtn** [comment]
Hi @tameraw,

When I  set the proxy directly on windows, it is not working either. I get a:
`WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).`

Do I need to configure something to let the SDK get the OS proxy settings?
Is this option will be supported eventually? I need a portable way to set proxy for the HTTP API on both Linux and Windows.

Thanks!

**Comment by tameraw** [comment]
@alexmrtn - One way to set it up would be thru the "Internet Options" control panel applet.
If you need this done programatically, would you be able to file a PR for this? Thanks.

**Comment by alexmrtn** [comment]
Hi,

I created a PR (https://github.com/Azure/azure-c-shared-utility/pull/126) as the default behavior of the SDK is not to fetch the OS configuration. With this fix, the SDK actually pick up the OS proxy settings.

I'll create later a new PR to set the proxy option in a programatically way.

**Comment by tameraw** [comment]
@alexmrtn thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
