### ISSUE TITLE
Azure_iot_sdk_c build failed with warning C4701

### ISSUE THREAD

**Issue by KarenHuang2016** [Azure/azure-c-shared-utility#118]
I build Azure_iot_sdk_c with Visual studio 2017 compiler on Windows Server 2016, but it failed with with warning C4701. could you help have a look about this issue? Thanks in advance!

**Failures:**
d:\azure_iot_sdk_c\src\iothub_client\src\uamqp_messaging.c(563): warning **C4701**: <func:#50 "_readMessageIdFromuAQMPMessage"> potentially uninitialized local variable 'result' used [D:\Azure_iot_sdk_c\build_x86\iothub_client\tests\uamqp_messaging_ut\uamqp_messaging_ut_exe.vcxproj]
         d:\azure_iot_sdk_c\src\iothub_client\src\uamqp_messaging.c(683): warning **C4701**: <func:#51 "_readCorrelationIdFromuAQMPMessage"> potentially uninitialized local variable 'result' used [D:\Azure_iot_sdk_c\build_x86\iothub_client\tests\uamqp_messaging_ut\uamqp_messaging_ut_exe.vcxproj]

**Repro steps:**
1. Open VS2017 x86 Native tools command tool
2. git clone --recursive http://www.github.com/azure/azure-iot-sdk-c D:\Azure_iot_sdk_c\src
3. cd D:\Azure_iot_sdk_c
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 -Drun_unittests:BOOL=ON ..\src\
6. msbuild azure_iot_sdks.sln /p:Configuration=Release /p:Platform=win32 /m /t:Rebuild

**Comment by tameraw** [comment]
@jebrando - Please confirm if fixed and close.

**Comment by jebrando** [comment]
I just built this with the latest SDK and it is working correctly.  @KarenHuang2016 Please reopen if you are still having issues.
