### ISSUE TITLE
Failed to build on OSX and gcc

### ISSUE THREAD

**Issue by mredd** [Azure/azure-c-shared-utility#128]
Hi folks,

I'm trying to build the c-utility as part of the azure-iot-sdk for C, but stumble right upon the first file to be compiled. GCC spits out an error log of 61 kB, so I'm putting this into an [attachment](https://github.com/Azure/azure-c-shared-utility/files/1438938/build.log) instead of pasting thousand lines of error messages here. Here are just the first two errors, because these are the ones repeated most:
```
In file included from <build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/umock_c_prod.h:23:0,
                 from <build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/buffer_.h:16,
                 from <build-dir>/azure-iot-sdk-src/c-utility/src/base32.c:8:
<build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/macro_utils.h:22951:51: error: unknown type name 'IF2'; did you mean 'IF'?
 #define IF(condition, trueBranch, falseBranch) C2(IF,ISZERO(condition))(trueBranch, falseBranch)
                                                   ^
<build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/macro_utils.h:6985:18: note: in definition of macro 'C2_'
 #define C2_(x,y) x##y
                  ^
<build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/macro_utils.h:22951:48: note: in expansion of macro 'C2'
 #define IF(condition, trueBranch, falseBranch) C2(IF,ISZERO(condition))(trueBranch, falseBranch)
                                                ^~
<build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/umock_c_prod.h:31:31: note: in expansion of macro 'IF'
     result modifiers function(IF(COUNT_ARG(__VA_ARGS__),,void) FOR_EACH_2_COUNTED(UMOCK_C_PROD_ARG_IN_SIGNATURE, __VA_ARGS__));
                               ^~
<build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/buffer_.h:20:1: note: in expansion of macro 'MOCKABLE_FUNCTION'
 MOCKABLE_FUNCTION(, BUFFER_HANDLE, BUFFER_new);
 ^~~~~~~~~~~~~~~~~
In file included from <build-dir>/azure-iot-sdk-src/c-utility/src/base32.c:8:0:
<build-dir>/azure-iot-sdk-src/c-utility/inc/azure_c_shared_utility/buffer_.h:20:1: error: macro "FOR_EACH_2_COUNTED_2" requires 3 arguments, but only 2 given
 MOCKABLE_FUNCTION(, BUFFER_HANDLE, BUFFER_new);
 ^~~~~~~~~~~~~~~~~~~~
```

I've tried to fix this on my own for two days now, but I'm totally lost in the utterly complex macro stuff you guys are doing there. And since this is the default build (I just ran cmake), I post this now as an issue to be hopefully fixed soon by the maintainers. Let me know if you need further input or some further tests to be conducted.

My environment is OSX 10.11.6 with homebrew's gcc 7.2.0. In contrast, the code builds without any warning when using Apple's clang (`Apple LLVM version 8.0.0 (clang-800.0.42.1)`).

Attachments:
[build.log](https://github.com/Azure/azure-c-shared-utility/files/1438938/build.log)

**Comment by ewertons** [comment]
Hey @mredd, sorry for the delay, we missed your question.
Are you still experiencing this error, or you found the solution?

Just so we have more info, what is the version of the SDK you are trying to build?

**Comment by mredd** [comment]
I'm just confused that the C-utility doesn't build when just checked out. I thought it was worth noticing the developers.

**Comment by tameraw** [comment]
@jebrando - Please confirm and close if fixed already. Thanks.

**Comment by jebrando** [comment]
The SDK build successfully on Mac.

**Comment by tameraw** [comment]
@mredd thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
