### ISSUE TITLE
uws_client_create throws Access violation reading location.

### ISSUE THREAD

**Issue by raaaar** [Azure/azure-c-shared-utility#139]
Repro (win32):
```
static const WS_PROTOCOL protocols[] = { { "test_protocol" } };
uws_client_create("test_host", 444, "/aaa", true, protocols, sizeof(protocols) / sizeof(protocols[0]));
```

looks like the hostname is not copied into tlsio_config.

The exception is raised in tlsio_schannel.c:995.

**Comment by jspaith** [comment]
Hi @raaaar.  Could you help us understand your scenario here?  Many of the c-utility API's are effectively private between it and a small number of repos we manage, so direct use isn't something we'd support.  Also related on #140.

If you're trying to use Azure IoT we do support web service access as a protocol and a *much* easier API to send and receive messages, decoratively model devices, etc.  Could you please look at https://github.com/Azure/azure-iot-sdk-c/ which is our public facing API and see if it meets you needs?
