### ISSUE TITLE
How to implement in other platform

### ISSUE THREAD

**Issue by pavankumar8279** [Azure/azure-c-shared-utility#144]
Hi 

I am learning IoT stuff 
I wanted to use this source in my code so that I can send packets as required by Azure IoT hub through GSM or Wifi module so how can I do that?
Is it a perfect source for my need?
what all libraries I need and how do I proceed?
I am writing a code in C language

thank you

**Comment by jebrando** [comment]
@pavankumar8279 Thanks, for the issue.  We will need to write up documentation on this.  We will add this to our todo list.

**Comment by hmxmghl** [comment]
@pavankumar8279 You will have to port the code of this utility to your platform by either writing the system calls on top of Hardware Abstraction Layer (HAL) or modifying the calls of this utility to match the existing calls specific to your platform. Former option is recommended.

**Comment by ericwol-msft** [comment]
This is simplified in the Azure embedded C SDK. https://github.com/Azure/azure-sdk-for-c
This SDK primarily targets windows and Linux SDK.
