### ISSUE TITLE
Segfault in tlsio_appleios

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-c-shared-utility#148]
Hi there,
My client crashes consistently when I build and run on MacOSX (10.10 and 10.12).
Specifically it's failing here in this function:
https://github.com/Azure/azure-c-shared-utility/blob/master/pal/ios-osx/tlsio_appleios.c#L526

I can't get the debugger to load at the moment, so haven't been able to get any more details.
I'm building the lib with the following options:
use_openssl:bool=OFF
use_default_uuid:bool=ON
use_builtin_httpapi:bool=ON
CMAKE_POSITION_INDEPENDENT_CODE=TRUE

The only linking is the two OSX frameworks:
`-framework Foundation -framework CFNetwork`

Have you seen this before?
Are there any known compatibility issues with different versions of OSX?

The client code that I'm running works successfully with OpenSSL on Linux, and Schannel on Windows. Are there any particular adjustments that need to be made to work with the Apple SSL?

Thanks,
Anna

**Comment by annatisch** [comment]
@jebrando, @JetstreamRoySprowl - any thoughts on this?

**Comment by JetstreamRoySprowl** [comment]
I've not seen a segfault in that function, so nothing presents itself immediately. The fact that the debugger won't load is suspicious, though. Are you using XCode or gnu?

**Comment by annatisch** [comment]
Thanks!
I'm actually using the lib through Python bindings - with gdb as the debugger. The debugger not loading is more an artifact of the Python build process I believe, rather than an issue in the client.
Build is with gcc.

**Comment by annatisch** [comment]
@JetstreamRoySprowl  - can I ask what build configuration options you use when running on OSX?

**Comment by JetstreamRoySprowl** [comment]
Sure! It's even public. Here's the script we do our [gcc compile](https://github.com/Azure/azure-iot-sdk-c/blob/bc9b67773348a44a87972a558288805650a7db38/jenkins/osx_gcc_openssl.sh#L17) with, and the [XCode compile is here](https://github.com/Azure/azure-iot-sdk-c/blob/bc9b67773348a44a87972a558288805650a7db38/jenkins/osx_xcode_native.sh#L20)

**Comment by JetstreamRoySprowl** [comment]
Sure! It's even public. The [gcc compile is here](https://github.com/Azure/azure-iot-sdk-c/blob/bc9b67773348a44a87972a558288805650a7db38/jenkins/osx_gcc_openssl.sh#L17), and the [XCode compile is here](https://github.com/Azure/azure-iot-sdk-c/blob/bc9b67773348a44a87972a558288805650a7db38/jenkins/osx_xcode_native.sh#L20).

**Comment by annatisch** [comment]
Thanks so much! I couple more questions:
- How do you get OpenSSL - do you build your own, or install using something like Homebrew?
- Have you confirmed compatibility across multiple OSX versions? (I intend to support as far back as 10.6)

**Comment by JetstreamRoySprowl** [comment]
* We don't have a solid prescription for how to use OpenSSL, probably because it's a giant can of worms. On Mac it seems to work with minimal tweaking (it was already installed on the machines I've worked with, but I don't know by what process), and on Windows I have to specify extra exports to make it run:
set OpenSSLDir=C:\OpenSSL-1.0.1
set OPENSSL_CONF=C:\OpenSSL-1.0.1
set OPENSSL_ROOT_DIR=C:\OpenSSL-1.0.1
Sorry I don't have more details.
* We haven't looked into OSX version compatibility yet. We only recently started using native Mac libraries for TLS, and only tested it on the latest (High Sierra).

**Comment by annatisch** [comment]
Interestingly I see that TLS 1.2 only because the default with High Sierra:
https://support.apple.com/en-us/HT207828

**Comment by jebrando** [comment]
@annatisch  I believe this should be fixed now.  Let me know if you're still seeing any issues.

**Comment by annatisch** [comment]
@jebrando - oh that's awesome! Thanks!! I will give it a try next time I build for release (hopefully this week).

**Comment by jebrando** [comment]
@annatisch We have done a few updates to this so if you see any more issues, please let me know.
