### ISSUE TITLE
How to use HTTPAPI to download data into a file?

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-c-shared-utility#150]
Hi,

I'm trying to use the HTTPAPI in order to download a file. This file may be too large to fit in memory but can be stored on the file system. As today, the `HTTPAPI_ExecuteRequest` function use an internal function `ContentWriteFunction` (for the curl implementation) that internally use a BUFFER_HANDLE to store the data in memory.

Do you think it could be possible to expose the callback function as an option in order to let the user handle receiving data in its own way? Maybe it is something you already think of?

Thanks,
Alexis.

**Comment by ewertons** [comment]
Hi @alexmrtn ,
apologies for the long delay. 
The issues in the parent repo (azure-iot-sdk-c) have higher priority and delay the response here.

We do not have plans to change the API at this moment. 
If you have a design in mind and would like to submit a PR we can work together on it.

**Comment by alexmrtn** [comment]
Hi @ewertons, 
No worries for the delay we also had some other priorities from our side, but this is still something we want to achieve.

We can definitely work on something together, I'll formalize an API change and submit a PR as you suggested. 

Thanks!

**Comment by ewertons** [comment]
Hi @alexmrtn ,
have you had a chance to put together a general description of the changes you need? 
Doesn't need to be a formal doc or anything, just the general lines of how you imagine this enhancement would be added to HTTPAPI.

**Comment by alexmrtn** [comment]
Hi @ewertons 
This is definitely a feature we want to add to enhance the HTTPAPI, unfortunately this was delayed in our priorities and I will not be able to formalize anything before next month. I'll post something here when available!

**Comment by ewertons** [comment]
Hi @alexmrtn ,
we completely understand. 
To maintain the list of issues groomed and up to date, we will close this issue then until we are ready to proceed. Once you have time again, please feel free to reopen it so we can reassess the design needed, perhaps discuss the possibility of getting a PR, etc.
Thanks and let us know whenever you would like to proceed.

**Comment by az-iot-builder-01** [comment]
@ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
