### ISSUE TITLE
UUID define in uuid.h collides with windows.h

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-c-shared-utility#162]
Including uuid.h and windows.h in the same project results in warnings of redefinition for UUID.
It would be awesome if uuid.h would choose a type name that is not really that widely used as to be present in windows.h.

Thanks!
/Dan

**Comment by ewertons** [comment]
Makes sense. We will try to address that soon.

**Comment by dcristoloveanu** [comment]
This has been addressed and it is merged into master.

**Comment by az-iot-builder-01** [comment]
@dcristoloveanu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
