### ISSUE TITLE
Azure blocks on receive after MBEDTLS_SSL_SERVER_CHANGE_CIPHER_SPEC

### ISSUE THREAD

**Issue by rutvij-trivedi** [Azure/azure-c-shared-utility#164]
Hi Folks,
I am new to this forum. 
I am trying to integrate azure c sdk to a custom hardware platform and to do so i followed https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/porting_guide.md porting document and changed platform related stuff as per doc.
I am using mbedtls_ssl_conf_authmode(&result->config, MBEDTLS_SSL_VERIFY_NONE) configuration with Lwip , freeRTOS and mbed TLS.

Now from the logs i can see that its trying do handshake and in handshake its able to exchange hello, but when it tries to do SERVER_CHANGE_CIPHER_SPEC it block on ssl->f_recv function and does nothing.

These are my logs i have added function lines in log for batter clarity.

#### Azure STARTER DEMO ####

Enter: iothub_client_sample_mqtt_run
ntp sync 
Enter: get_time

 [debug] IoTHubClientCore_LL after returning result 

#### SUCCESS : iotHubClientHandle is not NULL ####

 IoTHubClient_LL_SetMessageCallback...successful 

iterator: [0], callbackCounter: [0]. 
[debug]: Prepared text : {"deviceId":"myFirstDevice","windSpeed":14.00,"temperature":29.00,"humidity":62.00}
fun IoTHubMessage_CreateFromByteArray, line 136 
fun IoTHubMessage_CreateFromByteArray, line 146 
fun IoTHubMessage_CreateFromByteArray, line 157 
fun IoTHubMessage_CreateFromByteArray, line 167 
fun IoTHubMessage_CreateFromByteArray, line 179 
fun IoTHubMessage_CreateFromByteArray, line 191 
fun IoTHubMessage_CreateFromByteArray, line 214 
sending to cloud 
before Map_AddOrUpdate fun iothub_client_sample_run, line 186 
before IoTHubClient_LL_SendEventAsync fun iothub_client_sample_mqtt_run, line 191 
fun IoTHubClientCore_LL_SendEventAsync, line 1037 
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
fun iothub_client_sample_mqtt_run, line 200 
tickcounter currrent ms = 1104900
Callback to IoTHubTransport_DoWork
MQTT protocol
fun IoTHubTransport_MQTT_Common_DoWork, line 2613 
fun IoTHubTransport_MQTT_Common_DoWork, line 2618 
fun InitializeConnection, line 1927 
fun InitializeConnection, line 1933 
Enter: get_time
Enter: get_time
fun InitializeConnection, line 1940 
fun InitializeConnection, line 1943 
tickcounter currrent ms = 536998392
fun InitializeConnection, line 1953 
in else fun InitializeConnection, line 1956 
fun SendMqttConnectMsg, line 1799 
if fun SendMqttConnectMsg, line 1808 
Enter: get_time
Enter: get_difftime
Exit: get_difftime
fun SendMqttConnectMsg, line 1845 
fun xio_create, line 21 
fun xio_create, line 40 
fun xio_create, line 46 
fun tlsio_mbedtls_create, line 369 
fun tlsio_mbedtls_create, line 381 
fun tlsio_mbedtls_create, line 385 
fun tlsio_mbedtls_create, line 398 
fun tlsio_mbedtls_create, line 416 
fun xio_create, line 21 
fun xio_create, line 40 
fun xio_create, line 46 
fun socketio_create, line 141 
fun socketio_create, line 152 
fun socketio_create, line 164 
fun socketio_create, line 174 
fun tlsio_mbedtls_create, line 441 
fun mbedtls_init, line 335 
fun mbedtls_init, line 355 
fun mbedtls_init, line 362 
fun mbedtls_init, line 364 
fun tlsio_mbedtls_create, line 449 
fun SendMqttConnectMsg, line 1897 
fun mqtt_client_connect, line 977 
fun mqtt_client_connect, line 997 
fun cloneMqttOptions, line 474 
fun cloneMqttOptions, line 478 
fun cloneMqttOptions, line 489 
fun cloneMqttOptions, line 520 
fun cloneMqttOptions, line 545 
fun cloneMqttOptions, line 556 
fun cloneMqttOptions, line 567 
fun cloneMqttOptions, line 578 
fun cloneMqttOptions, line 589 
fun cloneMqttOptions, line 600 
fun xio_open, line 82 
fun xio_open, line 92 
fun xio_open, line 94 
fun tlsio_mbedtls_open, line 491 
fun tlsio_mbedtls_open, line 502 
fun tlsio_mbedtls_open, line 513 
fun xio_open, line 82 
fun xio_open, line 92 
fun xio_open, line 94 
fun socketio_open, line 222 
fun socketio_open, line 233 
fun socketio_open, line 242 

fun tcpsocketconnection_connect, line 49 
Socket creating ...
Socket created successfully 
tcpsocketconnection_connect SUCCESSFUL 

fun socketio_open, line 254 
fun tcpsocketconnection_set_blocking, line 23 
fun socketio_open, line 270 
fun socketio_open, line 273 
 result = 0 
fun on_underlying_io_open_complete, line 145 
fun on_underlying_io_open_complete, line 158 
fun on_underlying_io_open_complete, line 162 
fun mbedtls_ssl_handshake, line 6481 

=> handshake
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 0 //MBEDTLS_SSL_HELLO_REQUEST:
client state: 0
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 1 //MBEDTLS_SSL_CLIENT_HELLO,
client state: 1
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> write client hello
client hello, max version: [3:3]
client hello, current time: 1530597388
client hello, session id len.: 0
=> write record
output record: msgtype = 22, version = [3:3], msglen = 287
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2506 
message length: 292, out_left: 292
fun mbedtls_ssl_flush_output, line 2520 
fun mbedtls_ssl_flush_output, line 2523 
fun mbedtls_ssl_flush_output, line 2529 
<= flush output
fun mbedtls_ssl_flush_output, line 2539 
<= write record
<= write client hello
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 2 //MBEDTLS_SSL_SERVER_HELLO,
client state: 2
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
fun mbedtls_ssl_handshake_client_step, line 3375 
fun ssl_parse_server_hello, line 1393 
=> parse server hello
fun mbedtls_ssl_read_record, line 3804 
=> read record
fun mbedtls_ssl_read_record, line 3810 
fun mbedtls_ssl_read_record_layer, line 3844 
fun mbedtls_ssl_read_record_layer, line 3865 
fun mbedtls_ssl_read_record_layer, line 3875 
fun mbedtls_ssl_fetch_input, line 2229 
=> fetch input
fun mbedtls_ssl_fetch_input, line 2418 
in_left: 0, nb_want: 5
fun mbedtls_ssl_fetch_input, line 2422 
fun mbedtls_ssl_fetch_input, line 2425 
fun mbedtls_ssl_fetch_input, line 2432 
fun mbedtls_ssl_fetch_input, line 2446 
in_left: 0, nb_want: 5
in_left 0, nb_want 5 
fun mbedtls_ssl_fetch_input, line 2471 
<= fetch input
fun mbedtls_ssl_read_record_layer, line 3883 
input record: msgtype = 22, version = [3:3], msglen = 3710
fun mbedtls_ssl_fetch_input, line 2229 
=> fetch input
fun mbedtls_ssl_fetch_input, line 2418 
in_left: 5, nb_want: 3715
fun mbedtls_ssl_fetch_input, line 2422 
fun mbedtls_ssl_fetch_input, line 2425 
fun mbedtls_ssl_fetch_input, line 2432 
fun mbedtls_ssl_fetch_input, line 2446 
in_left: 5, nb_want: 3715
in_left 5, nb_want 3715 
fun mbedtls_ssl_fetch_input, line 2471 
<= fetch input
fun mbedtls_ssl_read_record_layer, line 3939 
fun mbedtls_ssl_read_record_layer, line 4047 
handshake message: msglen = 3710, type = 2, hslen = 81
fun mbedtls_ssl_read_record, line 3832 
<= read record
fun mbedtls_ssl_read_record, line 3838 
fun ssl_parse_server_hello, line 1473 
server hello, current time: 1530597390
fun ssl_parse_server_hello, line 1540 
fun ssl_parse_server_hello, line 1596 
server hello, session id len.: 32
fun ssl_parse_server_hello, line 1621 
fun ssl_parse_server_hello, line 1644 
no session has been resumed
server hello, chosen ciphersuite: c027
server hello, compress alg.: 0
fun ssl_parse_server_hello, line 1651 
fun ssl_parse_server_hello, line 1653 
server hello, chosen ciphersuite: TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA256
fun ssl_parse_server_hello, line 1668 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
fun ssl_parse_server_hello, line 1672 
server hello, total extension length: 5
fun ssl_parse_server_hello, line 1705 
found renegotiation extension
fun ssl_parse_server_hello, line 1842 
<= parse server hello
fun ssl_parse_server_hello, line 1902 
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 3  //MBEDTLS_SSL_SERVER_CERTIFICATE
client state: 3
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> parse certificate
fun mbedtls_ssl_read_record, line 3804 
=> read record
fun mbedtls_ssl_read_record, line 3810 
fun mbedtls_ssl_read_record_layer, line 3844 
fun mbedtls_ssl_read_record_layer, line 3849 
fun mbedtls_ssl_read_record_layer, line 3858 
handshake message: msglen = 3629, type = 11, hslen = 3264
fun mbedtls_ssl_read_record, line 3832 
<= read record
fun mbedtls_ssl_read_record, line 3838 
<= parse certificate
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 4 //MBEDTLS_SSL_SERVER_KEY_EXCHANGE
client state: 4
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> parse server key exchange
fun mbedtls_ssl_read_record, line 3804 
=> read record
fun mbedtls_ssl_read_record, line 3810 
fun mbedtls_ssl_read_record_layer, line 3844 
fun mbedtls_ssl_read_record_layer, line 3849 
fun mbedtls_ssl_read_record_layer, line 3858 
handshake message: msglen = 365, type = 12, hslen = 333
fun mbedtls_ssl_read_record, line 3832 
<= read record
fun mbedtls_ssl_read_record, line 3838 
ECDH curve: secp256r1
Server used SignatureAlgorithm 1
Server used HashAlgorithm 2
<= parse server key exchange
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 5  //MBEDTLS_SSL_CERTIFICATE_REQUEST
client state: 5
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> parse certificate request
fun mbedtls_ssl_read_record, line 3804 
=> read record
fun mbedtls_ssl_read_record, line 3810 
fun mbedtls_ssl_read_record_layer, line 3844 
fun mbedtls_ssl_read_record_layer, line 3849 
fun mbedtls_ssl_read_record_layer, line 3858 
handshake message: msglen = 32, type = 13, hslen = 28
fun mbedtls_ssl_read_record, line 3832 
<= read record
fun mbedtls_ssl_read_record, line 3838 
got a certificate request
Supported Signature Algorithm found: 6,1
Supported Signature Algorithm found: 6,3
Supported Signature Algorithm found: 4,1
Supported Signature Algorithm found: 5,1
Supported Signature Algorithm found: 2,1
Supported Signature Algorithm found: 4,3
Supported Signature Algorithm found: 5,3
Supported Signature Algorithm found: 2,3
<= parse certificate request
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 6 //MBEDTLS_SSL_SERVER_HELLO_DONE
client state: 6
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> parse server hello done
fun mbedtls_ssl_read_record, line 3804 
=> read record
fun mbedtls_ssl_read_record, line 3810 
fun mbedtls_ssl_read_record_layer, line 3844 
fun mbedtls_ssl_read_record_layer, line 3849 
fun mbedtls_ssl_read_record_layer, line 3858 
handshake message: msglen = 4, type = 14, hslen = 4
fun mbedtls_ssl_read_record, line 3832 
<= read record
fun mbedtls_ssl_read_record, line 3838 
<= parse server hello done
Hello server done !
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 7 //MBEDTLS_SSL_CLIENT_CERTIFICATE
client state: 7
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> write certificate
=> write record
output record: msgtype = 22, version = [3:3], msglen = 7
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2506 
message length: 12, out_left: 12
fun mbedtls_ssl_flush_output, line 2520 
fun mbedtls_ssl_flush_output, line 2523 
fun mbedtls_ssl_flush_output, line 2529 
<= flush output
fun mbedtls_ssl_flush_output, line 2539 
<= write record
<= write certificate
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 8  //MBEDTLS_SSL_CLIENT_KEY_EXCHANGE
client state: 8
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> write client key exchange
=> write record
output record: msgtype = 22, version = [3:3], msglen = 70
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2506 
message length: 75, out_left: 75
fun mbedtls_ssl_flush_output, line 2520 
fun mbedtls_ssl_flush_output, line 2523 
fun mbedtls_ssl_flush_output, line 2529 
<= flush output
fun mbedtls_ssl_flush_output, line 2539 
<= write record
<= write client key exchange
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 9  //MBEDTLS_SSL_CERTIFICATE_VERIFY
client state: 9
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> write certificate verify
=> derive keys
ciphersuite = TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA256
keylen: 16, minlen: 64, ivlen: 16, maclen: 32
<= derive keys
<= skip write certificate verify
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 10 //MBEDTLS_SSL_CLIENT_CHANGE_CIPHER_SPEC
client state: 10
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> write change cipher spec
=> write record
output record: msgtype = 20, version = [3:3], msglen = 1
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2506 
message length: 6, out_left: 6
fun mbedtls_ssl_flush_output, line 2520 
fun mbedtls_ssl_flush_output, line 2523 
fun mbedtls_ssl_flush_output, line 2529 
<= flush output
fun mbedtls_ssl_flush_output, line 2539 
<= write record
<= write change cipher spec
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 11 //MBEDTLS_SSL_CLIENT_FINISHED
client state: 11
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> write finished
=> calc  finished tls sha256
<= calc  finished
switching to new transform spec for outbound data
=> write record
=> encrypt buf
before encrypt: msglen = 80, including 16 bytes of IV and 16 bytes of padding
<= encrypt buf
output record: msgtype = 22, version = [3:3], msglen = 80
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2506 
message length: 85, out_left: 85
fun mbedtls_ssl_flush_output, line 2520 
fun mbedtls_ssl_flush_output, line 2523 
fun mbedtls_ssl_flush_output, line 2529 
<= flush output
fun mbedtls_ssl_flush_output, line 2539 
<= write record
<= write finished
fun mbedtls_ssl_handshake_client_step, line 3456 
fun mbedtls_ssl_handshake_step, line 6472 
fun mbedtls_ssl_handshake, line 6495 
fun mbedtls_ssl_handshake, line 6492 
fun mbedtls_ssl_handshake_step, line 6454 
fun mbedtls_ssl_handshake_step, line 6463 
fun mbedtls_ssl_handshake_client_step, line 3316 
client state: 12 //MBEDTLS_SSL_SERVER_CHANGE_CIPHER_SPEC
client state: 12
fun mbedtls_ssl_flush_output, line 2482 
=> flush output
fun mbedtls_ssl_flush_output, line 2499 
<= flush output
fun mbedtls_ssl_handshake_client_step, line 3329 
fun mbedtls_ssl_handshake_client_step, line 3353 
=> parse change cipher spec
=> parse change cipher spec
fun mbedtls_ssl_parse_change_cipher_spec, line 4639 
fun mbedtls_ssl_read_record, line 3804 
=> read record
fun mbedtls_ssl_read_record, line 3810 
fun mbedtls_ssl_read_record_layer, line 3844 
fun mbedtls_ssl_read_record_layer, line 3865 
fun mbedtls_ssl_read_record_layer, line 3875 
fun mbedtls_ssl_fetch_input, line 2229 
=> fetch input
fun mbedtls_ssl_fetch_input, line 2418 
in_left: 0, nb_want: 5
fun mbedtls_ssl_fetch_input, line 2422 
fun mbedtls_ssl_fetch_input, line 2425 
fun mbedtls_ssl_fetch_input, line 2432 
fun mbedtls_ssl_fetch_input, line 2446  //Blocks here and does nothing 

Can i get help in here.
Response would be appreciated.
Thank you !

**Comment by rutvij-trivedi** [comment]
Anyone alive ?

**Comment by jebrando** [comment]
@rutvij-trivedi Is this still an issue.  I believe that this may not be an issue any long. Let me know. Thanks.

**Comment by massand** [comment]
@rutvij-trivedi Thanks for reporting the issue. If you still into this problem with the latest fixes in tlsio_mbedtls, please let us know.

**Comment by az-iot-builder-01** [comment]
@rutvij-trivedi, @jebrando, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
