### ISSUE TITLE
OpenSSL on Windows

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/azure-c-shared-utility#17]
When I switch to OpenSSL on Windows I have a few issues:

1) tlsio_openssl_get_interface_description() in platform_win32.c hardcodes schannel
How to fix it for multiple library support?

2) SSL_library_init() is not called. 
It should be called in platform_init() put that is generic code.
See 1) about best way to add transport choices in platform_win32.c

3) tlsio_openssl_get_interface_description() hardcodes TLS1.0
Should be configurable.
 
4) No way to set SSL_CTX_set_cert_verify_callback()
Can't do it in application code because I need a pointer to SSL_CTX.
Which API should be extended?

**Comment by SparhawkSoftware** [comment]
I found xio_set_option which looks like it will be the best bet for setting the certificate verification callback. I guess it would work for TLS version too.

The only issue remaining is the best way to change  platform_win32.c  to handle switches between schannel and openssl.

**Comment by SparhawkSoftware** [comment]
Pull request submitted here: https://github.com/Azure/azure-c-shared-utility/pull/25

**Comment by dcristoloveanu** [comment]
Yep, platform_win32.c is the way to go.
I already merged your PR.
