### ISSUE TITLE
SNTP_Init blocking

### ISSUE THREAD

**Issue by xvinny-zz** [Azure/azure-c-shared-utility#179]
I'm currently developing a platform with two types of connection: GSM and WiFi.
When the platform connects, it initializes the communication with the Azure IoT server through platform_init function.
This function internally calls SNTP_Init (from pal\lwip\sntp_lwip.c), which tries to establish communication with the ntp server in order to get the current time.
The fact is.. if I have some problem in the GSM connection, like lack of prepaid funds, lack of signal or something that don't allow the data traffic, the function blocks inside the block:

```
	while (ts < 10 * 365 * 24 * 3600)
	{
		ThreadAPI_Sleep(1000);
		ts = get_time(NULL);

	}
```

I'd like to ask you to put a timeout feature in this function (and in the platform_init too).

Best regards

Vinicius

**Comment by ericwol-msft** [comment]
This is simplified in the Azure embedded C SDK. https://github.com/Azure/azure-sdk-for-c
This SDK primarily targets windows and Linux SDK.
