### ISSUE TITLE
Condition_Post on Windows will not 100% signal threads that call Condition_Wait

### ISSUE THREAD

**Issue by wes-b** [Azure/azure-c-shared-utility#189]
The issue is that Condition_Post will not signal an event for a thread that has called Condition_Wait 100% of the time, there is a race.

To use Condition_Post the caller must:
1)	Take lock
2)	Call Condition_Post();
        a.	In Condition_Post if waiting_thread_count != zero then signal event
3)	Release lock

This function is good because it evaluates waiting_thread_count inside the lock.

On the waiting thread, to use Condition_Wait the caller must:
1)	Take lock
2)	Call Condition_Wait() (internally Condition_Wait() does the following)
      a.	Release lock
      b.	++ waiting_thread_count;
      c.	WaitForSingleObject
      d.	Take lock
      e.	-- ‘waiting_thread_count’
3)	Release lock

This issue is that I can synchronize my two threads on the lock, and I can enter the Condition_Wait with the lock held, thread A is waiting for the lock about to call Condition_Post. Then on thread B Condition_Wait drops the lock before waiting_thread_count is increased, thread A can run, get the lock, call Condition_Post, and see the thread count is still zero, which means it won’t signal the event. Condition_Wait can then increment waiting_thread_count and then call WaitForSingleObject, which will lead to a timeout rather than a valid thread signal.

**Comment by dcristoloveanu** [comment]
@wes-b 

Thanks for the nice description, much appreciated.

Seems that the b.	++ waiting_thread_count; on the waiting thread should be done under a the lock.
If we agree that would solve it either of us can post the PR and the other one reviews :-).

Then I can merge it in.

Cheers, good catch!
/Dan

**Comment by wes-b** [comment]
@dcristoloveanu, yep, we agree on the fix. We will prepare a fix and submit a PR shortly.

**Comment by jspaith** [comment]
My review of 3d7c669cf92e804793b15c5ffeeec38480379fdc strongly suggests that this has been fixed.  There's no more Interlocked calls and my read of code is that `Condition_Wait` e.g. has `lock` held on invocation so that all potentially simultaneous changes of `waiting_thread_count` happen under lock.

Thanks @wes-b for issue & 3d7c669cf92e804793b15c5ffeeec38480379fdc change.
