### ISSUE TITLE
tickcounter_get_current_ms on Linux only has 1s resolution

### ISSUE THREAD

**Issue by wes-b** [Azure/azure-c-shared-utility#190]
Looks like internally its calling get_time_s instead of get_time_ns

**Comment by dcristoloveanu** [comment]
Hi @wes-b 
Sorry for the delay.
Indeed having something better than 1s resolution would be quite nice.

Either get_time_ns or clock_gettime with MONOTONIC (per https://linux.die.net/man/2/clock_gettime) would do fine.

Do you want to PR it? I don't see any issue with using either of those 2, I can review and merge, @jebrando can have an extra look as he cares more about Linux distro behavior atm.

Cheers,
/Dan

**Comment by wes-b** [comment]
Thanks for the link, we will prepare a fix soon and send out a PR.

**Comment by az-iot-builder-01** [comment]
@dcristoloveanu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
