### ISSUE TITLE
Condition_Init wrongly checks for INVALID_HANDLE_VALUE on CreateEvent

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-c-shared-utility#195]
Per https://github.com/Azure/azure-c-shared-utility/blob/19c551efd20f1a772963a585460e7e57740c976f/adapters/condition_win32.c#L31, 
Condition_Init wrongly checks for INVALID_HANDLE_VALUE on CreateEvent

MSDN says this should be a NULL check: https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-createeventa.

**Comment by danewalton** [comment]
fixed with https://github.com/Azure/azure-c-shared-utility/commit/3d7c669cf92e804793b15c5ffeeec38480379fdc
