### ISSUE TITLE
Condition on Win32 should be initialized by Interlocked APIs

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-c-shared-utility#196]
waiting_thread_count is being accessed by using Interlocked APIs, thus it should be initialized as such with InterlockedExchange.

**Comment by jspaith** [comment]
Resolving this because [this change](https://github.com/Azure/azure-c-shared-utility/commit/3d7c669cf92e804793b15c5ffeeec38480379fdc) removed Interlocked references in `condition_win32.c`.
