### ISSUE TITLE
CONST Buffer should perform one malloc only

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-c-shared-utility#197]
There's no need to have 2 mallocs to allocate the const buffer and handle information.
One should be enough.

**Comment by dcristoloveanu** [comment]
Merged in.

**Comment by az-iot-builder-01** [comment]
@dcristoloveanu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
