### ISSUE TITLE
Failed to transmit the data(via MQTT) after reception of data from server

### ISSUE THREAD

**Issue by ravitejaveeragandam** [Azure/azure-c-shared-utility#224]
Hi,

I taken the latest software and started working. Observed a strange behavior.

I will explain my scenario first
On power on i use to send 9 packets of data, each size of 14 bytes. And my program waits for response for the 9 packets what i sent. Once it get response it will send next packets.

With earlier software version 1.2.8, i am able to receive the response message and send the data(10th packet) one or two times and gets hang in "DoTimeouts".

But with software version 1.2.10, i am able to receive correct response for one of the 9 packets which i am sending and able to place next one packet data in IOT buffer to transfer. But from IOT i am unable to send the data to Server(not able to receive in TWIN device explorer). And also i confirmed that "SendConfirmationCallback" is not getting called.

Is there anything extra care i need to take in new software? I have doubt like did connection gets closed once after first transaction? Because every time i restart i am able to send the data.. Once after first transaction i am not able send data.

Note: Using function "IoTHubClient_LL_GetSendStatus" i got the status as "IOTHUB_CLIENT_SEND_STATUS_BUSY".

Control is not coming out of below loop
do
{
IoTHubClient_LL_DoWork(IOTHubClientHandle);
ThreadAPI_Sleep(10);

        IoTHubClient_LL_GetSendStatus(IOTHubClientHandle , &iothub_send_status);
                      
      } while (iothub_send_status == IOTHUB_CLIENT_SEND_STATUS_BUSY);

**Comment by YoDaMa** [comment]
@ravitejaveeragandam thanks for opening this issue. Can you enable logging and send in the logs you have from the code you are running? From what you've shared so far it's not clear what the issue might be. Also, sharing a sample snippet application that could be run to reproduce this issue that would be helpful and speed up the debugging process on this issue.

**Comment by YoDaMa** [comment]
@ravitejaveeragandam pinging again for logs.

**Comment by az-iot-builder-01** [comment]
@ravitejaveeragandam, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
