### ISSUE TITLE
Crash on iphone5c iOS 10.3.3

### ISSUE THREAD

**Issue by reddemonnet** [Azure/azure-c-shared-utility#229]
Application crashes on that line on iPhone 5c iOS 10.3.3

https://github.com/Azure/azure-c-shared-utility/blob/bcf6393b1ce3cecf0fcdf8988621fd6e4d414df3/pal/ios-osx/tlsio_appleios.c#L524

**Comment by massand** [comment]
@reddemonnet - is there specific sample code and call stack you can provide to reproduce this issue? There could be many likely scenarios your crash occurs, but it would be good to have more info before we investigate.

**Comment by dnsmirnoff** [comment]
#247 fixes that bug on devices with iOS 10.3.3

**Comment by dnsmirnoff** [comment]
Hello guys! Why you don't merge this fix?

**Comment by danewalton** [comment]
I believe this has been addressed with https://github.com/Azure/azure-c-shared-utility/pull/477. Please let us know if that is not hte case and we can revisit.
