### ISSUE TITLE
OpenSSL certificates option

### ISSUE THREAD

**Issue by rulez85** [Azure/azure-c-shared-utility#23]
I tried to execute the mssbcbs_sample with OpenSSL under Windows (no SChannel), but communication gets stuck since the client appears to be unable to verify the certificate provided by the Azure IoT Hub.
I noticed that in the websockets_sample with libwebsockets the IoT Hub certificates are provided in PEM format in the WSIO_CONFIG struct.
Is there a way to specify the same certificates when creating the TLSIO_CONFIG in the mssbcbs_sample as well?

**Comment by SparhawkSoftware** [comment]
I am working on a fix that allows the application to set the OpenSSL certificate callback as a xio option.
I hope to create the pull request in the next day or two.

**Comment by anhashia** [comment]
Looking at pull request #25

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Latest **develop** branch has fixes related to AMQP using  WebSocket. Please update to latest develop branch and test again.

**Comment by anhashia** [comment]
Closing this. Please re-activate if you have any further questions on this. Thanks !
