### ISSUE TITLE
error in tlsio_mbedtls.c

### ISSUE THREAD

**Issue by jflynn129** [Azure/azure-c-shared-utility#263]
@jebrando @massand 
There is a bug in 'tlsio_mbedtls_setoption' that causes a failure when connecting using MQTT transport, the following change needs to be added to correct (line #789):
```
             else if (strcmp(optionName, OPTION_UNDERLYING_IO_OPTIONS) == 0)
             {
                 result = 0;
             }

```

**Comment by massand** [comment]
@jflynn129 - thanks for the heads up on MBEDTLS. Which platform did you validate this fix in? 
@jebrando - this appears to be a quick fix. Although, we need to figure out our runtime validation for mbedTLS

**Comment by jflynn129** [comment]
The Avnet AT&&T IoT starter kit

**Comment by massand** [comment]
@jflynn129 I think your socket_io layer below tlsio_mbedtls needs to handle the OPTION_UNDERLYING_IO_OPTIONS value. tlsio_mbedtls will just pass it down. 
Also, the linked PR above has some fixes for tlsio_mbedtls which you will benefit from. Let us know how we can help further.

**Comment by momuno** [comment]
Hi @jflynn129 .  Was your original issue resolved?

**Comment by jflynn129** [comment]
Yes, long ago 🙂

**Comment by momuno** [comment]
@jflynn129 Thank you so much, and glad to hear it!
