### ISSUE TITLE
-Dno_logging:BOOL=ON produces linker errors

### ISSUE THREAD

**Issue by anporumb** [Azure/azure-c-shared-utility#291]
Linker say: 

XXXX.obj : error LNK2001: unresolved external symbol xlogging_get_log_function
XXXX.obj: error LNK2001: unresolved external symbol xlogging_get_log_function_GetLastError

It looks like when the project is generated with -Dno_logging and a LogLastError call is encountered in the code, it fails to link for the reason above.

**Comment by anporumb** [comment]
closed by https://github.com/Azure/azure-c-shared-utility/pull/383

**Comment by az-iot-builder-01** [comment]
@anporumb, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
