### ISSUE TITLE
Does HTTPAPI support persistent connection?

### ISSUE THREAD

**Issue by yinhew** [Azure/azure-c-shared-utility#299]
I mean the http 1.1 feature, with which you don't have to always setup connection with the server.
Does HTTPAPI support this?
If yes, how can I configure to enable it?

By default, I see it always took 1.x seconds for connection for each request.

**Comment by danewalton** [comment]
Hi @yinhew sorry for the delay here.

We have in curl the ability to set that as an option and it defaults to `0` so the same connection is attempted to be used:
https://github.com/Azure/azure-c-shared-utility/blob/f1f54ef5ef2b7e1be4bd750f17d1888bb6d07166/adapters/httpapi_curl.c#L408

For HTTPWin, that is by default the behavior https://microsoft.public.winhttp.narkive.com/9NM27MTE/keep-alive

For http compact, we do not currently have that as an option and likely won't in the future.
