### ISSUE TITLE
MbedTls errors on shutdown

### ISSUE THREAD

**Issue by massand** [Azure/azure-c-shared-utility#317]
On client disconnect (from MQTT), two specific calls to the mbedtls library throw errors:

socketio_send(CONCRETE_IO_HANDLE socket_io, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/socketio_berkeley.c:844)
xio_send(XIO_HANDLE xio, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:151)
**on_io_send(void * context, const unsigned char * buf, size_t sz) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:339)
mbedtls_ssl_flush_output (Unknown Source:0)
mbedtls_ssl_close_notify (Unknown Source:0)
tlsio_mbedtls_close(CONCRETE_IO_HANDLE tls_io, ON_IO_CLOSE_COMPLETE on_io_close_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:617)**
xio_close(XIO_HANDLE xio, ON_IO_CLOSE_COMPLETE on_io_close_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:118)
close_connection(MQTT_CLIENT * mqtt_client) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:79)
sendComplete(void * context, IO_SEND_RESULT send_result) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:199)
socketio_send(CONCRETE_IO_HANDLE socket_io, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/socketio_berkeley.c:900)
xio_send(XIO_HANDLE xio, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:151)
on_io_send(void * context, const unsigned char * buf, size_t sz) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:339)
mbedtls_ssl_flush_output (Unknown Source:0)
mbedtls_ssl_write_record (Unknown Source:0)
ssl_write_real (Unknown Source:0)
ssl_write_split (Unknown Source:0)
mbedtls_ssl_write (Unknown Source:0)
tlsio_mbedtls_send(CONCRETE_IO_HANDLE tls_io, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:651)
xio_send(XIO_HANDLE xio, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:151)
sendPacketItem(MQTT_CLIENT * mqtt_client, const unsigned char * data, size_t length) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:371)
mqtt_client_disconnect(MQTT_CLIENT_HANDLE handle, ON_MQTT_DISCONNECTED_CALLBACK callback, void * ctx) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:1209)
DisconnectFromClient(PMQTTTRANSPORT_HANDLE_DATA transport_data) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothubtransport_mqtt_common.c:1826)
IoTHubTransport_MQTT_Common_Destroy(TRANSPORT_LL_HANDLE handle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothubtransport_mqtt_common.c:2667)
IoTHubTransportMqtt_Destroy(TRANSPORT_LL_HANDLE handle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothubtransportmqtt.c:55)
IoTHubClientCore_LL_Destroy(IOTHUB_CLIENT_CORE_LL_HANDLE iotHubClientHandle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothub_client_core_ll.c:1696)
IoTHubDeviceClient_LL_Destroy(IOTHUB_DEVICE_CLIENT_LL_HANDLE iotHubClientHandle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothub_device_client_ll.c:51)
main() (/home/john/azure-iot-sdk-c2/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c:185)

...followed by...

socketio_send(CONCRETE_IO_HANDLE socket_io, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/socketio_berkeley.c:844)
xio_send(XIO_HANDLE xio, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:151)
on_io_send(void * context, const unsigned char * buf, size_t sz) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:339)
mbedtls_ssl_flush_output (Unknown Source:0)
mbedtls_ssl_close_notify (Unknown Source:0)
tlsio_mbedtls_close(CONCRETE_IO_HANDLE tls_io, ON_IO_CLOSE_COMPLETE on_io_close_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:617)
xio_close(XIO_HANDLE xio, ON_IO_CLOSE_COMPLETE on_io_close_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:118)
close_connection(MQTT_CLIENT * mqtt_client) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:79)
sendComplete(void * context, IO_SEND_RESULT send_result) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:199)
socketio_send(CONCRETE_IO_HANDLE socket_io, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/socketio_berkeley.c:900)
xio_send(XIO_HANDLE xio, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:151)
**on_io_send(void * context, const unsigned char * buf, size_t sz) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:339)
mbedtls_ssl_flush_output (Unknown Source:0)
mbedtls_ssl_write_record (Unknown Source:0)
ssl_write_real (Unknown Source:0)
ssl_write_split (Unknown Source:0)
mbedtls_ssl_write (Unknown Source:0)
tlsio_mbedtls_send(CONCRETE_IO_HANDLE tls_io, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/adapters/tlsio_mbedtls.c:651)
xio_send(XIO_HANDLE xio, const void * buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void * callback_context) (/home/john/azure-iot-sdk-c2/c-utility/src/xio.c:151)
sendPacketItem(MQTT_CLIENT * mqtt_client, const unsigned char * data, size_t length) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:371)
mqtt_client_disconnect(MQTT_CLIENT_HANDLE handle, ON_MQTT_DISCONNECTED_CALLBACK callback, void * ctx) (/home/john/azure-iot-sdk-c2/umqtt/src/mqtt_client.c:1209)**
DisconnectFromClient(PMQTTTRANSPORT_HANDLE_DATA transport_data) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothubtransport_mqtt_common.c:1826)
IoTHubTransport_MQTT_Common_Destroy(TRANSPORT_LL_HANDLE handle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothubtransport_mqtt_common.c:2667)
IoTHubTransportMqtt_Destroy(TRANSPORT_LL_HANDLE handle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothubtransportmqtt.c:55)
IoTHubClientCore_LL_Destroy(IOTHUB_CLIENT_CORE_LL_HANDLE iotHubClientHandle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothub_client_core_ll.c:1696)
IoTHubDeviceClient_LL_Destroy(IOTHUB_DEVICE_CLIENT_LL_HANDLE iotHubClientHandle) (/home/john/azure-iot-sdk-c2/iothub_client/src/iothub_device_client_ll.c:51)
main() (/home/john/azure-iot-sdk-c2/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c:185)

If possible, we should ensure xio_close() is called after all the mbedtls_ssl_* APIs are done being called.

**Comment by hihigupt** [comment]
Tried on latest release with mbedtls, not seeing any issue when call disconnect.
