### ISSUE TITLE
xlogging.h uses non ascii chars but does not encoded in UTF-8

### ISSUE THREAD

**Issue by yfakariya** [Azure/azure-c-shared-utility#32]
I noticed that `inc/azure_c_shared_utility/xlogging.h` is saved as Latin-1 encoding (for pretty single quotations in a comment), so it causes compilation error because of "treating warning as error" when the developer uses non Latin-1 code page console in Windows.
It is just messy when I build sources, but it is better and easy to save as UTF-8. Thanks!

**Comment by markrad** [comment]
Hi @yfakariya,

I'll take a look at this.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @yfakariya,

I concur. There are a small number of files in the SDK that are not encoded in UTF-8. I'll work with the product group to see if we can get that addressed.

_Mark Radbourne MSFT_

**Comment by jtanner-msft** [comment]
Hi @yfakariya,

  I have made the encoding changes to the file you referenced above.  It should be encoded as UTF-8 now in the C SDK on the develop branch, and all of the sub-projects as well.  
https://github.com/Azure/azure-iot-sdk-c.git
  If you observe any other files that are not UTF-8 please submit a new issue and we'll try to take care of it.
Thanks,
