### ISSUE TITLE
malloc() and free() are not changeable/portable

### ISSUE THREAD

**Issue by otg-abatec** [Azure/azure-c-shared-utility#329]
when using for example FreeRTOS it is desired to change the used function for malloc() and free()
to pvPortMalloc() and vPortFree(). IMHO calls to malloc()/free() shoud be renamed to something like X_malloc()/X_free(). And adapter code can be put inplace to redirect the X_malloc() calls to the desired allocation routine. As a simple example:

#define X_malloc(x) pvPortMalloc(x)

**Comment by jspaith** [comment]
Sorry for very long delay on this one as it had slipped through for a while.

First, we just officially released a middleware for FreeRTOS and Azure IoT.  It was designed from the ground up to be FreeRTOS centric.  For new projects we strongly recommend this over the current IoT C SDK/c-utility libraries.  The easiest way to get started is from [this repo](https://github.com/Azure-Samples/iot-middleware-freertos-samples).  Our new library does no mallocs to save every byte but only uses buffers app passes us, so `pvPortMalloc`|`vPortFree` would be mooted.

That said the existing c-utility does have the facilities to accomplish what you want.  If you set the cmake flag `use_custom_heap`,  what will happen is in `gballoc.h` we'll redefine malloc and friends to be `gballoc_malloc` and etc.  You can see how this is implemented for CRT in `gballoc.c` and at that point you could redirect these calls to be whatever you want.
