### ISSUE TITLE
Fill the gap for mbedtsl in httpapi_curl for certificates

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-c-shared-utility#336]
Hi,

We are moving from openssl to mbedtls as tls layer on a Linux platform. The curl implementation of HTTPAPI is missing mutual authentication capability (ie. https with client certificate). It is implemented for openssl and wolf ssl but not mbedTLS:

https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/httpapi_curl.c#L236-L283

I managed to add this capability by configuring mbedtls through the `ssl_ctx` in the same way it is done for the other ssl libraries. 

Are you willing to add this capability to the c-utility through a PR? If so, I can propose a x509_mbedtls.c file using the same philosophy as the ones for openssl and wolfssl.

**Comment by alexmrtn** [comment]
Hi,

I checked on the libcurl options and I was wondering why we do need to manually set the certificates in the [ssl_ctx_callback](https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/httpapi_curl.c#L221) function instead of using the [CURLOPT_SSLCERT](https://curl.haxx.se/libcurl/c/CURLOPT_SSLCERT.html) and [CURLOPT_SSLKEY](https://curl.haxx.se/libcurl/c/CURLOPT_SSLKEY.html) curl option? Doing so would remove the dependency on the tls layer used in HTTPAPI_curl.c

**Comment by rafilho** [comment]
Himanshu, could you please take a look on this issue? @alexmrtn has submitted a pull request to address it and I added you as a reviewer as well. Thanks.

**Comment by hihigupt** [comment]
@alexmrtn Thanks for sharing your pull request. 

Can you please share how you tested your changes?

**Comment by alexmrtn** [comment]
Hi

I tested the changes by generating a self signed CA then two certificates signed by this CA: one for the client and another one for the server. I then used `openssl s_server` with server certificate and option `-Verify` (Turn on peer certificate verification, must have a cert). I then connected to this server locally using the HTTPAPI with client certificate and the logs shown that the tls handshake went ok.

Note that I had to add in my `/etc/hosts` file a line with the localhost ip 127.0.0.1 and the hostname I gave in the server certificate (in the CN field) to make hostname verification works.

**Comment by hihigupt** [comment]
Can you please provide how you created environment that has curl lib configured with mbedlts. Did you rebuild source of curl with mbedlts enabled?

**Comment by alexmrtn** [comment]
I had to recompile libcurl with the following cmake flags: `-DCMAKE_USE_MBEDTLS=ON -DCMAKE_USE_OPENSSL=OFF` then using the usual `make && make install`

I also added these lines in my CMakeLists.txt that build the binary so that gcc can fetch the libcurl that I compiled and not the one from the system:
```
INCLUDE_DIRECTORIES(/usr/local/include)
LINK_DIRECTORIES(/usr/local/lib)
```

**Comment by hihigupt** [comment]
Merged.
https://github.com/Azure/azure-c-shared-utility/pull/368
