### ISSUE TITLE
compile wsio issue

### ISSUE THREAD

**Issue by enjoydiy** [Azure/azure-c-shared-utility#37]
home/wzj/openwrt/sdk_x1000/src/c-utility/src/wsio.c: In function 'wsio_open':
/home/wzj/openwrt/sdk_x1000/src/c-utility/src/wsio.c:782:21: error: 'lws_client_connect' is deprecated (declared at /home/wzj/openwrt/sdk_x1000/src/c-utility/deps/libwebsockets/lib/libwebsockets.h:2084) [-Werror=deprecated-declarations]
cc1: all warnings being treated as errors

**Comment by markrad** [comment]
Hi @enjoydiy,

I'm looking into this. Can you give me more detail about your platform and software versions. 

Thank you.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @enjoydiy,

Did you see my previous message? If you have not responded by the end of the week I will close this issue.
Thank you.

_Mark Radbourne MSFT
