### ISSUE TITLE
Meaningless condition in tlsio_mbedtls.c

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-c-shared-utility#376]
### Environment:
mbed TLS 2.16.2 branch released 2019-06-11
azure iot c sdk 1.3.4

### Issue descripton:
tlsio_mbedtls.c line: 989
`&tls_io_instance->owncert != NULL`

Struct member owncert is struct (not pointer) => address will be always non null value, the condition above is meaningless.

same issue apply for 
tlsio_mbedtls.c line: 993
`&tls_io_instance->pKey != NULL`

### Additional note

Structs are declared in following locations:

azure_iot\c-utility\adapters\tlsio_mbedtls.c
TLS_IO_INSTANCE           struct declared in tlsio_mbedtls, line 72

mbedtls\include\mbedtls\x509_crt.h
mbedtls_x509_crt          struct declared on line 53

mbedtls\include\mbedtls\pk.h
mbedtls_pk_context        struct declared on line 130

**Comment by hihigupt** [comment]
Thanks for reporting this. Changes are now merged into the azure-c-shared-utility master branch.

**Comment by az-iot-builder-01** [comment]
@DavidJurajdaNXP, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
