### ISSUE TITLE
Allow third alternative in `set_platform_files()` for bare-metal projects

### ISSUE THREAD

**Issue by FreddieChopin** [Azure/azure-c-shared-utility#379]
https://github.com/Azure/azure-c-shared-utility/blob/255cbc81a0f7bd2a34664503ce1f0276da5bb374/configs/azure_c_shared_utilityFunctions.cmake#L638

Currently `set_platform_files()` assumes that you are using either Linux/MacOS or Windows. This makes it extremely hard to port this project to a bare-metal platform, which uses a custom bare-metal RTOS (to be honest this is even harder because of how azure-iot-sdk-c build system is constructed, but this is a side note).

If you would like to add your own port _AND_ reuse existing build system of azure-iot-sdk-c, then you are out of luck and you either need to fork all the submodules or work with a snapshot (which will soon become outdated), because there is absolutely no way to tell the build system (without changing it!) to e.g. use `tickcounter_MyCustomRtos.c` instead of `tickcounter_linux.c`.

It seems to me that the easiest solution to this problem would be to allow a third alternative in `set_platform_files()`. The most flexible implementation of such feature would be for the function to set each variable (like `TICKCOUTER_C_FILE`) only if it is not already set - I would then set some of them (the ones which I would like to override) externally, in my parent `CMakeLists.txt`. There are other possible implementations of such feature, but they are less flexible then the one presented above.

Please let me know whether such feature would be desirable, I can provide a PR once I actually try that in the project.

**Comment by krokoko** [comment]
Up ? Interested as well
