### ISSUE TITLE
Error in CMakeLists.txt

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/azure-c-shared-utility#38]
Error in CMAKELISTS.txt:
The "crypt32 ws2_32 secur32" libs need to be added to the WIN32 option.
Do I need to do a pull request or can someone make the edit?

```
if(${use_openssl})
  if (WIN32)
    target_link_libraries(
       aziotsharedutil
       $ENV{OpenSSLDir}/lib/ssleay32.lib 
       $ENV{OpenSSLDir}/lib/libeay32.lib 
       crypt32 ws2_32 secur32)
    else()
        target_link_libraries(aziotsharedutil ssl crypto)
    endif()
endif()
```

**Comment by andrew-buckley** [comment]
Thanks @SparhawkSoftware. We're fixing this now, don't worry about creating a PR.

-Andrew

**Comment by andrew-buckley** [comment]
Hi @SparhawkSoftware, these libs have been added. Please have a look and close this issue if you conclude that it is resolved.

Thanks,
-Andrew
