### ISSUE TITLE
tlsio_mbed.c leaks ~6000 bytes

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-c-shared-utility#381]
SDK 1.3.4
[path]\azure-iot-sdk-c\c-utility\adapters
for the adaptation file `tlsio_mbed.c` when compiled with `use_mbedtls` option

If the device authenticates using x509 and the owner certificate is provided, the `mbedtls_uninit `function does not release the allocated chain.

Add the following line to the function to resolve it.
` mbedtls_x509_crt_free(&tls_io_instance->owncert);`

This is the modified function

```
// Un-initialize mbedTLS
static void mbedtls_uninit(TLS_IO_INSTANCE *tls_io_instance)
{
    if (tls_io_instance->tls_status != TLS_STATE_NOT_INITIALIZED)
    {
        // mbedTLS cleanup...
        mbedtls_x509_crt_free(&tls_io_instance->trusted_certificates_parsed);
        //This is needed to clear the Ecc certificate
        mbedtls_x509_crt_free(&tls_io_instance->owncert);  //<== ADD this line or leak occurs
        mbedtls_pk_free(&tls_io_instance->pKey);
        mbedtls_ssl_free(&tls_io_instance->ssl);
        mbedtls_ssl_config_free(&tls_io_instance->config);
        mbedtls_ctr_drbg_free(&tls_io_instance->ctr_drbg);
        mbedtls_entropy_free(&tls_io_instance->entropy);


        tls_io_instance->tls_status = TLS_STATE_NOT_INITIALIZED;
    }
    else
    {
        LogError("Uninitialzing when not previously initialized");
    }
}
```

**Comment by hihigupt** [comment]
Thanks for reporting this. Changes are now merged into the azure-c-shared-utility master branch.

**Comment by az-iot-builder-01** [comment]
@uriel-kluk, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
