### ISSUE TITLE
Problem with getting a snapshot from ip camera using http api

### ISSUE THREAD

**Issue by Gep-Kistler** [Azure/azure-c-shared-utility#39]
Hello,

I tried to get snapshots from ip camera using http api in my implementation of Azure field gateway (using Azure Gateway IoT SDK). I have the following code: 
```C
#define HOST_NAME (const char*)"96.10.1.168"
#define RELATIVE_PATH (const char*)"/axis-cgi/jpg/image.cgi?resolution=640x480"

HTTPAPI_Init();

unsigned int statusCode;
HTTPAPI_RESULT result;
HTTP_HEADERS_HANDLE requestHttpHeaders;
HTTP_HEADERS_HANDLE responseHttpHeaders;
BUFFER_HANDLE bufferHandle;
HTTP_HANDLE httpHandle = HTTPAPI_CreateConnection(HOST_NAME);
requestHttpHeaders = HTTPHeaders_Alloc();
responseHttpHeaders = HTTPHeaders_Alloc();
bufferHandle = BUFFER_new();

result = HTTPAPI_ExecuteRequest(
	httpHandle,
	HTTPAPI_REQUEST_GET,
	RELATIVE_PATH,
	requestHttpHeaders,
	NULL,
	0,
	&statusCode,
	responseHttpHeaders,
	bufferHandle);

HTTPHeaders_Free(requestHttpHeaders);
requestHttpHeaders = NULL;
HTTPHeaders_Free(responseHttpHeaders);
responseHttpHeaders = NULL;
BUFFER_delete(bufferHandle);
HTTPAPI_CloseConnection(httpHandle);
HTTPAPI_Deinit();
```
I built this code in VS2015 and run it on the Win10. However, I still get the following error:
Error: Time:Wed Nov 30 15:52:10 2016 File:C:\azure-iot-gateway-sdk\deps\c-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:437 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Wed Nov 30 15:52:10 2016 File:C:\azure-iot-gateway-sdk\deps\c-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:437 GetLastError: The operation timed out

BTW, 96.10.1.168 is the publicly available ip camera and the request http://96.10.1.168/axis-cgi/jpg/image.cgi?resolution=640x480 works well in browser or postman. Any idea, what's wrong with http api?

Best Regards,
Peter

**Comment by Gep-Kistler** [comment]
Similar issue (or even worse) with the same code I found also on Ubuntu 16.04:
Error: Time:Thu Dec  1 16:34:07 2016 File:/azure-iot-gateway-sdk/deps/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:534 curl_easy_perform() failed: Couldn't connect to server

Error: Time:Thu Dec  1 16:34:07 2016 File:/azure-iot-gateway-sdk/deps/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:536 (result = HTTPAPI_OPEN_REQUEST_FAILED)

**Comment by markrad** [comment]
Hi @Gep-Kistler,

Can you provide me with the complete source file so that I can test it from myself please?

Thank you

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @Gep-Kistler,

Don't bother with the source. I looked at the curl adaptor implementation. It is hardcoded to assume all websites are using SSL, i.e. it appends the hostname with https. The website you are attempting to read does not have SSL enabled hence it fails.

You will need to use an alternative mechanism to read the webpage.

_Mark Radbourne MSFT_

**Comment by Gep-Kistler** [comment]
Hi Mark,

It's strange that SSL is hard code. I found it convenient to use http api in te Azure IoT gateway's module implementation as I need to take snapshots from IP camera and send them to Azure. Which multiplatform http library written in c do you recommend to use? I would prefer that http api in "Azure C sared utility" would ave parametrized use of SSL.

Peter

**Comment by markrad** [comment]
Hi @Gep-Kistler,

I'm looking at the code to see how much effort it would be to support http without ssl. I'll get back to you.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
I'm still looking at this. Since there are multiple adapters for the HTTP protocol it is rather more complex to implement than I anticipated. I'm trying to convince the product group that they should make this change.

_Mark Radbourne MSFT_

**Comment by tameraw** [comment]
@Gep-Kistler - Currently this is not a priority in the backlog. If this is still of interest to you, we would welcome a contribution on this. Regards.
