### ISSUE TITLE
Support modern cmake style by using `target_link_libraries` to model dependencies

### ISSUE THREAD

**Issue by dandrestor** [Azure/azure-c-shared-utility#396]
Currently including this cmake project as a sub-directory (i.e. using `add_subdirectory`) in a larger cmake build does not work, because dependencies are not modeled correctly.
Please consider adding something similar to the following, which would enable this (diff is against commit f0642196)

```diff
--- a/c-utility/CMakeLists.txt
+++ b/c-utility/CMakeLists.txt
@@ -461,7 +461,7 @@ if(${build_as_dynamic})
     set_target_properties(aziotsharedutil_dll PROPERTIES OUTPUT_NAME "aziotsharedutil_dll")
 endif()
 
-set(aziotsharedutil_target_libs)
+set(aziotsharedutil_target_libs umock_c azure_macro_utils_c)
 
 if(${logerror_captures_stack_traces})
     set(aziotsharedutil_target_libs ${aziotsharedutil_target_libs} Dbghelp.lib)
```

**Comment by ericwol-msft** [comment]
we will not be refactoring these CMake files for this SDK repo.
