### ISSUE TITLE
Add support for libcurl compiled with NSS

### ISSUE THREAD

**Issue by zeroepoch** [Azure/azure-c-shared-utility#40]
Fedora by default builds curl using NSS instead of OpenSSL  This causes the Azure IoT gateway samples to segfault while trying to establish a connection to the iothub.  With help from @andrew-buckley it was determined that building curl with OpenSSL support and setting `LD_LIBRARY_PATH` to use the libcurl compiled with OpenSSL fixes the problem.  You can find more information in this issue: https://github.com/Azure/azure-iot-gateway-sdk/issues/62

**Comment by tameraw** [comment]
@zeroepoch  - Closing as this has not bubbled up in priority. If still an issue or blocking on your side, please reopen. Thanks.
