### ISSUE TITLE
LOG_INFO of LOG_CATEGORY_TAG should be changed to another name.

### ISSUE THREAD

**Issue by tkanoh** [Azure/azure-c-shared-utility#41]
Since the variable name LOG_INFO conflicts with the variable used  by the Linux standard logging system in /usr/include/syslog.h, it is better to use a different name.

**Comment by anporumb** [comment]
Thank you for your report. I will be working on this issue.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Have renamed LOG_INFO to AZ_LOG_INFO. Do open another issue if that did not solve it.

Best Regards,
Andrei Porumb
