### ISSUE TITLE
Incorrect verification of OptionHandler functions results

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-c-shared-utility#411]
These result verifications are incorrect.
They may cause failures if the enum value differs from the corresponding int value tested on if blocks.

tlsio_wolfssl.c:                (OptionHandler_AddOption(result, SU_OPTION_X509_CERT, tls_io_instance->x509certificate) != 0)
tlsio_wolfssl.c:                (OptionHandler_AddOption(result, SU_OPTION_X509_PRIVATE_KEY, tls_io_instance->x509privatekey) != 0)
tlsio_wolfssl.c:                (OptionHandler_AddOption(result, OPTION_TRUSTED_CERT, tls_io_instance->certificate) != 0)

archive/cyclonessl/tlsio_cyclonessl.c:                (OptionHandler_AddOption(result, "TrustedCerts", tls_io_instance->certificate) != 0)

**Comment by ewertons** [comment]
This has been fixed.

**Comment by az-iot-builder-01** [comment]
@ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
