### ISSUE TITLE
Terminate a thread by using ThreadAPI_Exit()

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-c-shared-utility#418]
Ported on behalf of @Hmaalla from original issue: https://github.com/Azure/azure-iot-sdk-c/issues/1348
---
Hello,
We are using the multithreading abstraction layer given by the "c - utility" to develop a multithreading application.
We have some memory leaks if we exit a thread by calling ThreadAPI_Exit () without joining it with ThreadAPI_Join ().
If fact, the free of "threadHandle" ressources is done only by calling ThreadAPI_Join ().
The question here, it's possible to free "threadHandle" also in ThreadAPI_Exit () to give more flexibility to the user to exit the created thread without joining it?

**Comment by ewertons** [comment]
@hmaalla, 
the design of ThreadAPI_Exit and ThreadAPI_Join follow the implementation of the major thread libraries. Modifying our libraries to deviate from the expected behavior from native libraries (e.g., pthread in Linux) would go against a proper and reliable design.

If you verify how pthread works, you will notice that not calling pthread_join will cause memory leaks (even if you are calling pthread_exit from within the thread function).
Here is an example of verification using valgrind:

```bash
==29361== HEAP SUMMARY:
==29361==     in use at exit: 2,998 bytes in 9 blocks
==29361==   total heap usage: 11 allocs, 2 frees, 4,078 bytes allocated
==29361==
==29361== 1,360 bytes in 5 blocks are possibly lost in loss record 5 of 5
==29361==    at 0x4C31B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29361==    by 0x40134A6: allocate_dtv (dl-tls.c:286)
==29361==    by 0x40134A6: _dl_allocate_tls (dl-tls.c:530)
==29361==    by 0x4E44227: allocate_stack (allocatestack.c:627)
==29361==    by 0x4E44227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29361==    by 0x108867: main (main.c:21)
==29361==
==29361== LEAK SUMMARY:
==29361==    definitely lost: 0 bytes in 0 blocks
==29361==    indirectly lost: 0 bytes in 0 blocks
==29361==      possibly lost: 1,360 bytes in 5 blocks
==29361==    still reachable: 1,638 bytes in 4 blocks
==29361==         suppressed: 0 bytes in 0 blocks
==29361== Reachable blocks (those to which a pointer was found) are not shown.
==29361== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==29361==
==29361== For counts of detected and suppressed errors, rerun with: -v
==29361== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

So the correct way would be to work on your design so you can call ThreadAPI_Join from the same layer that has invoked ThreadAPI_Create.

**Comment by Hmaalla** [comment]
@ewertons 
Thanks a lot for the feedback.

**Comment by danewalton** [comment]
This seems to be a closed issue.
