### ISSUE TITLE
Unable to set trusted certificate for HTTPAPI (Windows)

### ISSUE THREAD

**Issue by YannGirard** [Azure/azure-c-shared-utility#425]
## config 
 master 
windows 10

Hello,

We are encountering a problem using azure-iot-sdk-c\c-utility\adapters\httpapi_winhttp.c.
We are trying tu use the option "OPTION_TRUSTED_CERT" inside HTTPAPI_SetOption() function.
The issue is that it always returns 0 as a result.
As you can see in
[this line](https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/httpapi_winhttp.c#L1020)
When the optionName parameter is set to OPTION_TRUSTED_CERT and if everything goes well, result is set to 0 (result is a type HTTPAPI_RESULT).

As you can see at
[this line](https://github.com/Azure/azure-macro-utils-c/blob/master/inc/azure_macro_utils/macro_utils.h#L88)
on Windows, HTTPAPI_RESULT = 0 correspond to HTTPAPI_RESULT = MU_FAILURE and not HTTPAPI_OK hence the problem which forbids us to use our trusted certificate on Windows.

Could you help us with this issue ?

**Comment by az-iot-builder-01** [comment]
@YannGirard, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by YannGirard** [comment]
Yes, it is working fine now.

Thanks
