### ISSUE TITLE
MacOS: Setting trusted certs would get "Trusted certs option not supported"

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-c-shared-utility#426]
Hi,

I find that on MacOS (10.15.2) when trying to set "TrustedCerts" on tlsio, the `tlsio_options_set` function would always fail.

The reason is that:

1) in the `tlsio_options_set` method, the if-statement is checking `supported_options &  
 TLSIO_OPTION_BIT_TRUSTED_CERTS` [(coe here)](https://github.com/Azure/azure-c-shared-utility/blob/831c6b365599276cac17aa0d37960b44d21e0e00/pal/tlsio_options.c#L155-L159).
```c
    else if (strcmp(OPTION_TRUSTED_CERT, optionName) == 0)
    {
        if ((options->supported_options & TLSIO_OPTION_BIT_TRUSTED_CERTS) == 0)
        {
            LogError("Trusted certs option not supported");
            result = TLSIO_OPTIONS_RESULT_ERROR;
        }
```
2) However, when creating tlsio instance on MacOS, the options is set to `TLSIO_OPTION_BIT_NONE` [(code here)](https://github.com/Azure/azure-c-shared-utility/blob/831c6b365599276cac17aa0d37960b44d21e0e00/pal/ios-osx/tlsio_appleios.c#L261).
```c
tlsio_options_initialize(&result->options, TLSIO_OPTION_BIT_NONE);
// ----------------- In tlsio_options.c ---------------
// Initialize the TLSIO_OPTIONS struct
void tlsio_options_initialize(TLSIO_OPTIONS* options, int supported_options)
{
    // Using static function rules, so 'options' is not checked for NULL
    //
    // The supported_options value does not need validation because undefined bits are
    // ignored, while any valid missing bits result in an "option not supported" error
    // that will show up in unit testing.
    options->supported_options = supported_options;
    options->trusted_certs = NULL;
    options->x509_type = TLSIO_OPTIONS_x509_TYPE_UNSPECIFIED;
    options->x509_cert = NULL;
    options->x509_key = NULL;
}
```

These two places are inconsistent leading to the issue. Is this the designed behavior? If not, then what's the proper way of setting `TrustedCerts` on a MacOS tlsio?

Related issue:
https://github.com/Azure/azure-sdk-for-python/issues/7201#issuecomment-582271921

**Comment by az-iot-builder-01** [comment]
@yunhaoling, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by yunhaoling** [comment]
PR: https://github.com/Azure/azure-c-shared-utility/pull/427/ merged
