### ISSUE TITLE
AMQP on Linux not appearing to send SNI causing Azure Firewall to drop connections

### ISSUE THREAD

**Issue by milope** [Azure/azure-c-shared-utility#428]
Hello Team,

After troubleshooting an incident, we noticed Azure Firewall was dropping AMQP connections due to a missing SNI header. This issue reproduces on Linux but not Windows. After reviewing some of the source code, it appears when running on Windows, the SDK uses SChannel vs Open SSL when running on Linux when defaulted. According to the WIKI, OpenSSL appears to require SSL_set_tlsext_host_name to be called in order to send an SNI extension.

**ASK:** While it appears servers like Azure Service Bus do not require an SNI to route traffic, Python libraries that have this library as a dependency (uAMQP) would not be able to perform outbound connections behind a service like Azure Firewall. Azure Firewall application rules require TLS connections to include an SNI header to evaluate rules as without the SNI header, it cannot determine which FQDN the client intends to talk. Can we request to have the code to call

`SSL_set_tlsext_host_name`

So that it sends the SNI extension when using Open SSL on Linux? At least a search here doesn't show this call being used to initialize the SSL_CTX object.

**Comment by danewalton** [comment]
this looks to be closed with #453
