### ISSUE TITLE
Build for OpenWRT+musl failed

### ISSUE THREAD

**Issue by truebiker** [Azure/azure-c-shared-utility#438]
Hello Team,

We build azure-iot-sdk-c (2019-12-11) as a package for OpenWRT. It is ok for OpenWRT 14.04 which is based on uClibc C library. Now we are migrating to newer version 18.06 which is based on musl C library. Latter differs from uClibc by adding
> "#warning redirecting incorrect #include <sys/errno.h> to <errno.h>"

directive to <sys/errno.h> file (usually <sys/errno.h> just silently include <errno.h>). Azure-iot-sdk-c (and most of its deps) in turn uses ``-Werror`` build flag which leads to build failure. I manually fixed all instances of ``socket_async_os.h`` (from root of azure-iot-sdk-c through all deps) to include <errno.h> for now using OpenWRT patch mechanism. But it can break build in future when upgrade to newer version of azure-iot-sdk-c due to new tools become dependent on c-utility or new include of <sys/errno.h>. Could you propose the right fix for this issue?

**Comment by pboettch** [comment]
I just got the same problem. Have you submitted a pull-request?

**Comment by truebiker** [comment]
> I just got the same problem. Have you submitted a pull-request?

No. We added an overlay patch to OpenWRT that fixes the issue.

**Comment by pboettch** [comment]
But I think your fix is correct. Would you mind me creating a PR for that?

**Comment by truebiker** [comment]
I don't mind. But I didn't provide any fixes)) I just have a patch in my local tree. I can share it.

**Comment by pboettch** [comment]
No, your fix is correct. Userspace should not include `sys/errno.h` but `errno.h`.

**Comment by pboettch** [comment]
It has been fixed actually on master branch. 665326f6492966d4387d3581bd9bcb6a10245ea3

Now user-projects should be updated or this commit should be cherry-picked on the LTS-branch.

**Comment by truebiker** [comment]
Great!
Thank you.

**Comment by az-iot-builder-01** [comment]
@truebiker, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
