### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by pengwinsurf** [Azure/azure-c-shared-utility#439]
Hi, 

Looking at azure-uamqp-python (https://github.com/Azure/azure-uamqp-python/blob/master/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/pal/dns_async.c). There is a dns_asyn.c file which only supports ipv4 atm. 

I am in an environment that is only ipv6. Thus I cannot connect to eventhub because of the dependancy here on this shared utility that only supports ipv4. I am having to use blob storage for an event hub scenario unfortunately. 

Any chance ipv6 would be added here and subsequently in azure-uamqp-python ? 

Thanks

**Comment by ewertons** [comment]
Hi @pengwinsurf ,
unfortunately we have no immediate plans of supporting IPv6. It is not even supported on Azure IoT Hub as of now.
You can track the customer feature request [here](https://feedback.azure.com/forums/321918-azure-iot/suggestions/35374537-add-support-for-ipv6-on-azure-iot-hub).

**Comment by az-iot-builder-01** [comment]
@pengwinsurf, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
