### ISSUE TITLE
seems a dead loop in readChunk method

### ISSUE THREAD

**Issue by yulin-li** [Azure/azure-c-shared-utility#443]
In the [readChunk](https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/httpapi_compact.c#L603) method in `httpapi_compact.c`, if the `conn_receive` returns -1 (xio reported error on dowork), the while loop will never exit.

**Comment by az-iot-builder-01** [comment]
@yulin-li, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by danewalton** [comment]
https://github.com/Azure/azure-c-shared-utility/pull/444

Seems we closed the issue mistaking the "merged" icon for your fork to be our repo when culling through issues. This fix has been merged and now this is properly closed.
