### ISSUE TITLE
xio issue

### ISSUE THREAD

**Issue by sngpt08** [Azure/azure-c-shared-utility#45]
Hi 

I have built this for Arch64 but when I am running my receiver it got stuck... at this function "xio_open".
I have checked the return value of this xio_open and its returning success but none of the registered callback is getting called. 

Is I am missing something ??

**Comment by anporumb** [comment]
Hello @sngpt08 ,

We need more context to be able to help you. What's your version of Arch64?

What are you running as a sample? What's the SHA-1 of the repo you are trying to use? 

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
We will close this now, if you come back with more details, feel free to reopen.

Best Regards,
Andrei Porumb
