### ISSUE TITLE
replace CryptAcquireContext

### ISSUE THREAD

**Issue by bitbegin** [Azure/azure-c-shared-utility#459]
As the document said:
```
Important  This API is deprecated. New and existing software should start using Cryptography Next Generation APIs. Microsoft may remove this API in future releases.
```
this function should be replaced by CNG api.

https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptacquirecontexta

**Comment by ericwol-msft** [comment]
This is still supported in WIndows 11.
