### ISSUE TITLE
creating a socket IO implementation documentation

### ISSUE THREAD

**Issue by mtbrewster** [Azure/azure-c-shared-utility#46]
In the porting guide the section on creating a socket IO implementation just has To be filled in as shown below.

Creating a socket IO implementation

This is needed if an existing out of the box TLS adapter is used.

To be filled in.

**Comment by anporumb** [comment]
Hello @mtbrewster ,

Thanks for reporting this, we will have a look at adding the socketio section as soon as we have time.

Best Regards,
Andrei Porumb

**Comment by massand** [comment]
The porting guide seems up to date - https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/tlsio_requirements.md

Please reopen  if there is any gaps. Thanks.

**Comment by az-iot-builder-01** [comment]
@mtbrewster, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
