### ISSUE TITLE
porting_guide.md references non-existent file in azure-c-shared-utility

### ISSUE THREAD

**Issue by gshera** [Azure/azure-c-shared-utility#468]
The [porting_guide.md tlsio-adapter-implementation](https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/porting_guide.md#tlsio-adapter-implementation) references the **dns_resolver.c** in the repository [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility) however this file no longer exist in master.

**Comment by danewalton** [comment]
Hi @gshera this looks to be fixed with this commit [here](https://github.com/Azure/azure-c-shared-utility/commit/f37168b99f98380d5804c9554f87efde2b1b87d0#diff-4343018254176bcf5ce656a6341e8fe61a5d8051cf99dbe3c3c639da23c6568e). Thanks for bringing it to our attention!
