### ISSUE TITLE
Ported to Azure Sphere?

### ISSUE THREAD

**Issue by stefan-hudelmaier** [Azure/azure-c-shared-utility#469]
Hi, 

I was wondering if anyone has ported this library to Azure Sphere?

**Comment by danewalton** [comment]
Azure Sphere has their own version of the SDK on the device. Details can be found [here](https://docs.microsoft.com/en-us/azure-sphere/app-development/baseapis#azure-iot-c-sdk-library). No porting needed!

**Comment by stefan-hudelmaier** [comment]
Thanks for getting back to me. The problem is that I need a websocket client for an Azure Sphere program and I thought I could use the one from azure-c-shared-utility.

**Comment by danewalton** [comment]
Ahh sorry forgot this is on the c-shared repo and not the C SDK. There is some documentation [here](https://docs.microsoft.com/en-us/azure-sphere/app-development/baseapis#azure-iot-c-sdk-library-features) which states that the HTTP is turned off which leads me to believe that natively it isn't possible (you probably already knew that based on your question). I can say that we don't have it. I might suggest you issue a feedback item [here](https://feedback.azure.com/forums/915433-azure-sphere) for them to add the functionality.

**Comment by danewalton** [comment]
@stefan-hudelmaier Going to close this for now for inactivity. If you would like to reopen please just leave a message here on the issue.

**Comment by az-iot-builder-01** [comment]
@danewalton, @stefan-hudelmaier, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
