### ISSUE TITLE
tickcounter_get_current_ms is creating run-time check failure #2 - stack around the variable was corrupted

### ISSUE THREAD

**Issue by mohakraaj** [Azure/azure-c-shared-utility#47]
Changing line 102 to *current_ms = (tickcounter_ms_t)(tick_counter_instance->current_ms / 1000) gets away with this run time error.  (Intermittently)

**Comment by anporumb** [comment]
Hello @mohakraaj ,

Thank you for your report. At the moment I would like to better understand the context where this appears. 

Can you please attach here a minimal repro?

Best Regards,
Andrei Porumb

**Comment by BertKleewein** [comment]
I can't see how that change would have any effect.  I just looked at the assembly that this code produces under x86 debug and it's identical before and after your change.  What flavor are you building with and what compiler are you using?

Before the change:
```
; 101  : 
; 102  :                 *current_ms = tick_counter_instance->current_ms / 1000;

  00190	8b 4d f4	 mov	 ecx, DWORD PTR _tick_counter_instance$6[ebp]
  00193	8b 41 18	 mov	 eax, DWORD PTR [ecx+24]
  00196	33 d2		 xor	 edx, edx
  00198	b9 e8 03 00 00	 mov	 ecx, 1000		; 000003e8H
  0019d	f7 f1		 div	 ecx
  0019f	8b 55 0c	 mov	 edx, DWORD PTR _current_ms$[ebp]
  001a2	89 02		 mov	 DWORD PTR [edx], eax
```

After your change:
```
; 101  : 
; 102  :                 *current_ms = (tickcounter_ms_t)(tick_counter_instance->current_ms / 1000);

  00190	8b 4d f4	 mov	 ecx, DWORD PTR _tick_counter_instance$6[ebp]
  00193	8b 41 18	 mov	 eax, DWORD PTR [ecx+24]
  00196	33 d2		 xor	 edx, edx
  00198	b9 e8 03 00 00	 mov	 ecx, 1000		; 000003e8H
  0019d	f7 f1		 div	 ecx
  0019f	8b 55 0c	 mov	 edx, DWORD PTR _current_ms$[ebp]
  001a2	89 02		 mov	 DWORD PTR [edx], eax
```

**Comment by anporumb** [comment]
Closing this, Please reopen if you still have the issue.

Best Regards,
Andrei Porumb
