### ISSUE TITLE
There is a small leak on tlsio_mbedtls.c

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-c-shared-utility#474]
mbedtls_uninit is missing the mbedtls_ssl_session_free line:

```
// Un-initialize mbedTLS
static void mbedtls_uninit(TLS_IO_INSTANCE *tls_io_instance)
{
    if (tls_io_instance->tls_status != TLS_STATE_NOT_INITIALIZED)
    {
        // mbedTLS cleanup...
        mbedtls_ssl_free(&tls_io_instance->ssl);
        mbedtls_ssl_config_free(&tls_io_instance->config);

mbedtls_ssl_session_free(&tls_io_instance->ssn); //<= without this the code leaks a few bytes everytime it reconnects
 
       mbedtls_x509_crt_free(&tls_io_instance->trusted_certificates_parsed);
        mbedtls_x509_crt_free(&tls_io_instance->owncert);
        mbedtls_pk_free(&tls_io_instance->pKey);
        mbedtls_ctr_drbg_free(&tls_io_instance->ctr_drbg);
        mbedtls_entropy_free(&tls_io_instance->entropy);

        tls_io_instance->tls_status = TLS_STATE_NOT_INITIALIZED;
    }
    else
    {
        LogError("Uninitialzing when not previously initialized");
    }
}
```

**Comment by danewalton** [comment]
Hi @uriel-kluk thanks for the report. I'll double check and report back here.

**Comment by danewalton** [comment]
Seeing as we are init'ing it here:
https://github.com/Azure/azure-c-shared-utility/blob/0ed4867678768978a0d46bd07042ce06dca02e9f/adapters/tlsio_mbedtls.c#L491

and the compliment to that can be seen to be the free:
https://tls.mbed.org/api/ssl_8h.html#ac085defe1a02ab784a0a2fb201bcc741

Yup I believe you are right! I have a PR open [here](https://github.com/Azure/azure-c-shared-utility/pull/475) to fix it. Note that we have to propagate the submodules up so you won't see the fix immediately. But it will make its way to here.

Thanks for the find!

**Comment by az-iot-builder-01** [comment]
@uriel-kluk, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
