### ISSUE TITLE
cannot compile the project successfully on Ubuntu 16.04 desktop

### ISSUE THREAD

**Issue by liu-xiao-guo** [Azure/azure-c-shared-utility#48]
liuxg@liuxg:~/snappy/desktop/azure-c-shared/cmake$ cd make ...
bash: cd: make: No such file or directory
liuxg@liuxg:~/snappy/desktop/azure-c-shared/cmake$ cd make ..
bash: cd: make: No such file or directory
liuxg@liuxg:~/snappy/desktop/azure-c-shared/cmake$ cmake ..
-- Shared_Util architecture: x86_64
CMake Error at testtools/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /home/liuxg/snappy/desktop/azure-c-shared/testtools/ctest

  does not contain a CMakeLists.txt file.

CMake Error at testtools/CMakeLists.txt:10 (add_subdirectory):
  The source directory

    /home/liuxg/snappy/desktop/azure-c-shared/testtools/testrunner

  does not contain a CMakeLists.txt file.

CMake Error at testtools/CMakeLists.txt:11 (add_subdirectory):
  The source directory

    /home/liuxg/snappy/desktop/azure-c-shared/testtools/umock-c

  does not contain a CMakeLists.txt file.

-- iothub architecture: x86_64
-- Configuring incomplete, errors occurred!
See also "/home/liuxg/snappy/desktop/azure-c-shared/cmake/CMakeFiles/CMakeOutput.log".

**Comment by anporumb** [comment]
Hello @liu-xiao-guo ,

I am guessing you did not use --recursive on the command line.

When you clone the repo, you much use --recursive on the command line. That will populate the submodules and bring in the CMakeLists.txt that are not found.

Let me know if that solves your problem.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Closing this, Please reopen if you still have the issue.

Best Regards,
Andrei Porumb
