### ISSUE TITLE
TLSIO on macOS is unable to detect network down

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-c-shared-utility#487]
Hey, I'm from the azure-sdk-for-python team working on azure-servicebus/azure-eventhub. As you may know, we use azure-uamqp-python (who is built on top of azure-uamqp-c and azure-c-shared-utility).

Recently there is a customer reporting that our azure-servicebus sdk is unable to recovery/report error on macOS when there's a network down, it would end up looping forever: https://github.com/Azure/azure-sdk-for-python/issues/15473.

I checked the implementation of the tlsio_appleios.c finding that `dowork_read` is only checking the socket status of `kCFStreamStatusAtEnd`, not checking any other status which doesn't seem correct.
https://github.com/Azure/azure-c-shared-utility/blob/master/pal/ios-osx/tlsio_appleios.c#L428-L432
```python
        if (read_status == kCFStreamStatusAtEnd)
        {
            enter_tlsio_error_state(tls_io_instance);
        }
```

according to the [apple's documentation](https://developer.apple.com/documentation/corefoundation/cfstreamstatus): `kCFStreamStatusError indicates an error occurred on the stream.`.
so I think `kCFStreamStatusError` should also be checked and in this case, the program should go into `enter_tlsio_error_state` as well. I have tried the code and after checking the error status, the connection error could be bubbled up properly.

I've made a small PR to address this: https://github.com/Azure/azure-c-shared-utility/pull/486

Let me know if I miss anything important or you have any concern on this.

**Comment by danewalton** [comment]
should be merged now thanks for the heads up!

**Comment by az-iot-builder-01** [comment]
@yunhaoling, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
