### ISSUE TITLE
does not build with libressl

### ISSUE THREAD

**Issue by asac** [Azure/azure-c-shared-utility#50]
libressl [dropped FIPS_mode_set](http://marc.info/?l=openbsd-misc&m=139819485423701&w=2).

For me the following would work at least. Don't think it would hurt anyone with pristine openssl either, so maybe consider this:
```
diff --git a/src/tlsio_openssl.c b/src/tlsio_openssl.c
index 5cd805b..a9db3c1 100644
--- a/src/tlsio_openssl.c
+++ b/src/tlsio_openssl.c
@@ -930,7 +930,9 @@ void tlsio_openssl_deinit(void)
 {
     openssl_dynamic_locks_uninstall();
     openssl_static_locks_uninstall();
+#ifndef LIBRESSL_VERSION_NUMBER
     FIPS_mode_set(0);
+#endif
     CRYPTO_set_locking_callback(NULL);
     CRYPTO_set_id_callback(NULL);
     ERR_free_strings();
```

**Comment by anporumb** [comment]
Hello @asac ,

We have a fix checked in master branch and will close the issue once we publish packages.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Published.
