### ISSUE TITLE
How to connect to a proxy which requires ssl certificate and client certificate

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-c-shared-utility#501]
hey,

We're having a scenario that we want to connect to azure service via a proxy that requires ssl certificate (server certificate) and client certificate (client-side certificate) for client to authenticate the identity of the proxy server and proxy server to authenticate the identity of the client.

I found that the [http_proxy_io.c](https://github.com/Azure/azure-c-shared-utility/blob/master/src/http_proxy_io.c) only allows for setting username and password, it doesn't allow setting certificates and it has no underlying io settings (interface/config stuff).

Is it supported in the current library?
if it's supported, could you share me with the sample code how it works.

**Comment by ericwol-msft** [comment]
Yes, it only supports "Basic" auth.

**Comment by yunhaoling** [comment]
hey @ericwol-msft , I have made a PR which allows for the http proxy io to be built on top of tlsio: https://github.com/Azure/azure-c-shared-utility/pull/512.

through this way, the server side tls certificate could be set on the underlying tlsio.

I'm not sure whether you have a guideline for the design, but I think we could collaborate on this together. :)

**Comment by ewertons** [comment]
@yunhaoling , thank you for your work on this feature.
Although we recognize you really put an effort on putting a PR together with the changes you needed for HTTP to be supported over TLS, at this point we do not plan on taking that into our code base as we have not reserved resources for curating and maintaining the changes. We will thus close this issue. 
But again, thank you for your insights, and we will definitely revisit it if we find broader request for HTTPS PROXY support.
Azure IoT SDK Team.
