### ISSUE TITLE
compilation for mbed failed due to incorrect include path

### ISSUE THREAD

**Issue by yaweiw** [Azure/azure-c-shared-utility#55]
[ERROR] /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/socketio_mbed.c:14:58: fatal error: azure_c_shared_utility/tcpsocketconnection_c.h: No such file or directory
 #include "azure_c_shared_utility/tcpsocketconnection_c.h"

/azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/tcpsocketconnection_c.cpp:8:58: fatal error: azure_c_shared_utility/tcpsocketconnection_c.h: No such file or directory

#include "tcpsocketconnection_c.h" works the magic.

**Comment by anporumb** [comment]
Hello @yaweiw ,

Can you please provide a minimal repro here? We want to repro it, but we do not know what you've done to get that error.

Best Regards,
Andrei Porumb

**Comment by yaweiw** [comment]
hi @anporumb, 
if you take a look at "inc/azure_c_shared_utility/", tcpsocketconnection_c.h isn't in there. Instead, it's under azure-c-shared-utility/adapters/. Not sure if there is any build script that will copy this header file to inc/ azure_c_shared_utility/. We build a docker container to do the build that run into this error. Any suggestions?

The build script is:
FILES="--source /azure-iot-devkit/scripting-engine/duktape/src

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/agenttime_mbed.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/httpapi_compact.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/threadapi_rtx_mbed.cpp

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/tickcounter_mbed.cpp

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/socketio_mbed.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/adapters/tcpsocketconnection_c.cpp

       --source /azure-iot-devkit/device/mbed/platform_mbed.cpp

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/base64.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/buffer.c 

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/connection_string_parser.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/consolelogger.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/constbuffer.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/constmap.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/crt_abstractions.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/doublylinkedlist.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/gb_stdio.c 

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/gb_time.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/gballoc.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/hmacsha256.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/hmac.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/httpapiex.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/httpapiexsas.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/httpheaders.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/map.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/optionhandler.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/sastoken.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/sha1.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/sha224.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/sha384-512.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/singlylinkedlist.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/string_tokenizer.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/strings.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/tlsio_wolfssl.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/urlencode.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/usha.c 

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/vector.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/xio.c

       --source /azure-iot-devkit/azure-iot-sdk-c/c-utility/src/xlogging.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/blob.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothub_client.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothub_client_ll.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothub_message.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothubtransport.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothubtransportmqtt.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c

       --source /azure-iot-devkit/azure-iot-sdk-c/umqtt/src

       --source /azure-iot-devkit/azure-iot-sdk-c/parson/parson.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/version.c

       --source /azure-iot-devkit/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c

       --source /azure-iot-devkit/azure-iot-sdk-c/certs/certs.c

       --source /azure-iot-devkit/wolfSSL/src/crl.c

       --source /azure-iot-devkit/wolfSSL/src/internal.c

       --source /azure-iot-devkit/wolfSSL/src/io.c

       --source /azure-iot-devkit/wolfSSL/src/keys.c

       --source /azure-iot-devkit/wolfSSL/src/ocsp.c

       --source /azure-iot-devkit/wolfSSL/src/sniffer.c

       --source /azure-iot-devkit/wolfSSL/src/ssl.c

       --source /azure-iot-devkit/wolfSSL/src/tls.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/aes.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/arc4.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/asm.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/asn.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/blake2b.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/camellia.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/chacha.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/chacha20_poly1305.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/coding.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/compress.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/curve25519.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/des3.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/dh.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/dsa.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/ecc.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/ecc_fp.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/ed25519.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/error.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/fe_low_mem.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/fe_operations.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/ge_low_mem.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/ge_operations.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/hash.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/hc128.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/hmacx.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/integer.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/logging.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/md2.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/md4.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/md5.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/memory.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/misc.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/pkcs7.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/poly1305.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/pwdbased.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/rabbit.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/random.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/ripemd.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/rsa.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/sha.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/sha256.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/sha512.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/tfm.c

       --source /azure-iot-devkit/wolfSSL/wolfcrypt/src/wc_port.c

       --source /azure-iot-devkit/device/mbed/ESP8266Interface.cpp

       --source /azure-iot-devkit/device/mbed/UDPSocket.cpp

       --source /azure-iot-devkit/device/mbed/Endpoint.cpp

       --source /azure-iot-devkit/device/mbed/TCPSocketServer.cpp

       --source /azure-iot-devkit/device/mbed/TCPSocketConnection.cpp

       --source /azure-iot-devkit/device/mbed/Socket.cpp

       --source /azure-iot-devkit/device/mbed/ESP8266.cpp

       --source /azure-iot-devkit/scripting-engine/duktape/bindings

       --source /azure-iot-devkit/scripting-engine/bindings

       --source /azure-iot-devkit/NTPClient/NTPClient.cpp

       --source /azure-iot-devkit/device/mbed/mbed-main.cpp

       --source /azure-iot-devkit/device/mbed/iot-thread.cpp

       --source /azure-iot-devkit/device/mbed/iot-storage.c

       --source /azure-iot-devkit/device/mbed/iot-wifi.cpp

       --source /azure-iot-devkit/device/mbed/iot-dbgprint.cpp

       --source /azure-iot-devkit/app-generic.c"



rm -rf /mbed-app/mbed-os/features/netsocket



cd /mbed-app/

mbed compile -t GCC_ARM -m NUCLEO_F411RE --profile /azure-iot-devkit/device/mbed/mbed-custom.json -c --source=mbed-os $FILES --build=/azure-iot-devkit/build

cd /azure-iot-devkit

**Comment by yaweiw** [comment]
@anporumb

**Comment by anporumb** [comment]
Hello @yaweiw ,

We find it awesome that you have a docker container. Can we have it too? We'd like to integrate that in our gated process.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @yaweiw ,

We have a fix checked in "master" branch. Can you please confirm the fix? Thank you.

Best Regards,
Andrei Porumb
