### ISSUE TITLE
HTTPAPI_SetOption for cURL returns always OK for some options

### ISSUE THREAD

**Issue by AlexandreMarechalSE** [Azure/azure-c-shared-utility#56]
Hi,

I was facing issue by setting certificates for the HTTP_API.
After reviewing the code of httpapi_curl.c I realize that setting option for:

- SU_OPTION_X509_CERT
- SU_OPTION_X509_PRIVATE_KEY

Always returned HTTPAPI_OK

Branch: master
also on 
Tag: 2017-02-10 (line 681 and 711)

Thanks

Alexandre

**Comment by zolvarga** [comment]
Hi Alexandre,

Thank you for reporting this. I am working on the fix and will let you know when it is checked in.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
HI Alexandre,

The fix has been checked in.

Best Regards,
Zoltan

**Comment by AlexandreMarechalSE** [comment]
Hi @zolvarga 

Thank you for correcting the issue.

Regards,
Alexandre
