### ISSUE TITLE
WolfSSL layer UT don't actually ASSERT on expected calls

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-c-shared-utility#575]
Many examples in file but as just one the one at bottom of this post.

The `STRICT_EXPECTED_CALL` is to make sure we properly invoke the layer under in the stack but... it needs to actually be checked against a call to `ASSERT_ARE_EQUAL(char_ptr, umock_c_get_expected_calls(), umock_c_get_actual_calls());` to actually verify what was expected happened.  This ASSERT is missing.

I'm recording this as part of an unrelated change but suggests we should look at other UT to see if there's a similar pattern.  While I've never liked the checking linkedList additions are succesful, with a mock framework seeing that the expected calls to mocked-out, lower layer does add value.

```c
TEST_FUNCTION(tlsio_wolfssl_on_io_recv_timeout_success)
{
    //arrange
    char recv_buff[BUFFER_LEN];
    TLSIO_CONFIG tls_io_config;
    memset(&tls_io_config, 0, sizeof(tls_io_config));
    tls_io_config.hostname = TEST_HOSTNAME;
    CONCRETE_IO_HANDLE io_handle = tlsio_wolfssl_create(&tls_io_config);
    // ensure we stay in the handshake mode
    g_handshake_done_cb = NULL;
    (void)tlsio_wolfssl_open(io_handle, on_io_open_complete, NULL, on_bytes_recv, NULL, on_error, NULL);
    umock_c_reset_all_calls();

    for (size_t index = 0; index < WOLFSSL_READ_LIMIT; index++)
    {
        STRICT_EXPECTED_CALL(xio_dowork(IGNORED_PTR_ARG));
    }

    //act
    int test_result = g_wolfssl_cb_rcv(TEST_WOLFSSL, recv_buff, BUFFER_LEN, g_wolfssl_rcv_ctx);

    //assert
    ASSERT_ARE_EQUAL(int, 0, test_result);

    //clean
    (void)tlsio_wolfssl_close(io_handle, on_close_complete, NULL);
    tlsio_wolfssl_destroy(io_handle);
}
```

**Comment by momuno** [comment]
Moving this to internal backlog item.
