### ISSUE TITLE
Visual Studio 14 Win64 compilation issue.

### ISSUE THREAD

**Issue by piotrzaremba** [Azure/azure-c-shared-utility#58]
I am having issues compiling the library using /TP.

I use the cmake-gui to create a default Visual Studio 14 Win64 solution.
I select properties -> C/C++/Advanced/Compile As within Visual Studio.
I receive several compilation issues.  Any suggestions?

**Comment by zolvarga** [comment]
Hi piotrzaremba,

Please provide more details about the compilation issue you are having. 
We are compiling our with VS 14 for 64 bit on our gate. and if you follow the installation and use steps you should be able to have it compiled cleanly.

Best Regards,
Zoltan

**Comment by mhshami01** [comment]
Hello piotrzaremba,

Thank you for your submission. At this point, using "/TP" for the azure IoT C SDK is not supported and is not being considered.

Best Regards,
Haitham

**Comment by piotrzaremba** [comment]
Sorry for the late reply thanks for the enhancement tag.  I could list out the issues I was encountering, however it mainly revolved around math.h/cmath.h collision between same name method difinitions e.g. abs().  I am integrating a c++ engine with Azure Event Hub and that is how I ran into the issue since the c++ engine is compiled /TP.

**Comment by tameraw** [comment]
@piotrzaremba - If this is still a blocking issue, please reopen. Thanks.
