### ISSUE TITLE
not able to cross compile "azure-shared-utility"

### ISSUE THREAD

**Issue by sandeepnpatil** [Azure/azure-c-shared-utility#581]
when i started cross compiling iot-hub-device-update-main for AMR platform, i found it depends on "azure-c-shared-utility" and further azure-c-shared-utility is depends on macro-utils-c and umock-c.
while resolving dependencies there was a error of not able to install "umock_cFunctions.cmake" there was not much articles on google also.
if i comment out umock_cFunctions.cmake and try to cross compile "

error: comparison of integer expressions of different signedness: ‘int’ and ‘CONSTMAP_RESULT’ {aka ‘enum CONSTMAP_RESULT_TAG’} [-Werror=sign-compare]
![screen1](https://user-images.githubusercontent.com/53256991/150324701-eacaf094-072e-4ecf-931b-9a339c9b18c8.png)
![screen2](https://user-images.githubusercontent.com/53256991/150324742-3b8a8eeb-83ec-441b-b4da-e8a3c16327cf.png)

**Comment by sandeepnpatil** [comment]
i am using below Ubuntu version
Linux bsp-VM 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danewalton** [comment]
Hi @sandeepnpatil 
Can you make sure your submdoules are correctly initiazlied?

```bash
git submodule update --init --recursive
```

**Comment by sandeepnpatil** [comment]
yes submodules are in place, still issue persists
![image](https://user-images.githubusercontent.com/53256991/151540651-932be237-8fa9-4eba-8234-ed69509ce331.png)

**Comment by danewalton** [comment]
Are you able to share the exact code base which you are compiling? I'd like to check versions and configurations of the SDK

**Comment by sandeepnpatil** [comment]
i am using master branch only, are you asking about same code base?

**Comment by danewalton** [comment]
It looks like your submodules are all being placed in the `/microsoft` directory? Each repository should have it's own submodules. If you are building the `Azure/azure-c-shared-utility` specifically, you should clone and initialize submodules. Please try the following flow exactly:

```bash
git clone git@github.com:Azure/azure-c-shared-utility.git
cd azure-c-shared-utility
git submodule update --init --recursive
mkdir cmake
cd cmake
cmake ..
cmake --build .
```

**Comment by momuno** [comment]
@sandeepnpatil did the above comments from @danewalton help you solve the issue?

**Comment by danewalton** [comment]
Closing this for now for inactivity. Please let us know if you would like it reopened.
