### ISSUE TITLE
Unable to build azure_c_shared_utility

### ISSUE THREAD

**Issue by fkavache** [Azure/azure-c-shared-utility#582]
I'm on the latest commit
Submodule is updated (git submodule update --init --recursive)

[Note] I'm updating from [1.1.11](https://github.com/Azure/azure-c-shared-utility/releases/tag/1.1.11) tag to master branch

Here is the screenshot
![image](https://user-images.githubusercontent.com/29062515/152557240-1140f7d6-2b62-49a0-b7e5-c67721b1f633.png)

**Comment by fkavache** [comment]
I'm getting this error while trying to build on Linux

![image](https://user-images.githubusercontent.com/29062515/152799919-b23d95cf-5415-47de-b5c6-5fecfb512aff.png)

**Comment by ericwol-msft** [comment]
check your cmake include paths. Is it an issue because the directory name is azure_c_shared and not azure-c-shared?

**Comment by fkavache** [comment]
Hi @ericwol-msft

Thank you for your response,
I'm just having **add_subdirectory(azure_c_shared)** which then includes CMake from the **azure-c-shared-utility** source

**Comment by momuno** [comment]
@fkavache were you able to build azure_c_shared_utility?

**Comment by danewalton** [comment]
Closing this for now for inactivity. Please let us know if you would like it reopened.
