### ISSUE TITLE
25 Warnings in IOT code

### ISSUE THREAD

**Issue by SadanandPenore-eaton** [Azure/azure-c-shared-utility#599]
Hello Team,
We have integrated the Azure library in our project based on Zephyr OS.
We are getting 25 warnings as seen in attachement. Can you please help is resolving this. There is a mandatory requirement to have zero warnings in project.

[25 Azure Code Warnings.txt](https://github.com/Azure/azure-c-shared-utility/files/8850209/25.Azure.Code.Warnings.txt)

**Comment by wduraes** [comment]
Hi @SadanandPenore-eaton thank you for letting us know about this issue. I'm adding this to our backlog and should get this resolved soon.

**Comment by SadanandPenore-eaton** [comment]
Thank you @wduraes ,
Any update on this. Can you provide tentative timeline for fixing?

**Comment by JoseSanchez7** [comment]
Hello @SadanandPenore-eaton , may you please confirm all the compile options that were passed and used during the compilation process?

**Comment by danewalton** [comment]
Hi @SadanandPenore-eaton any chance you can share particulars with your build environment?

**Comment by danewalton** [comment]
It looks like many of the warnings are coming from code outside of our repository like 	`tlsio_mbedtls.cpp`, `socketio_ltk.cpp`, `IOT_Example.cpp` and `iot_serialization.c`. Are you only looking for the solving of the warnings from our code which looks to be in  `iothub_internal_consts.h` and `iothubtransport_mqtt_common.c`?

**Comment by SadanandPenore-eaton** [comment]
I will get back shortly with the required inputs.

**Comment by JoseSanchez7** [comment]
Hello @SadanandPenore-eaton, just following up regarding the required inputs.

**Comment by JoseSanchez7** [comment]
@SadanandPenore-eaton We resolved the issues that were being caused by code in the SDK. Please respond with an update if you need further assistance.
