### ISSUE TITLE
ReleaseSemaphore fails (Nuget update to 1.0.29) 

### ISSUE THREAD

**Issue by PJ1980** [Azure/azure-c-shared-utility#60]
I just updated (via nuget) to 1.0.29 and am now experiencing the following issue:
Error: Time:Sat Mar 11 21:38:55 2017 File:c:\a\azure-iot-sdk-c\c-utility\adapters\lock_win32.c Func:_Unlock Line:106 ReleaseSemaphore failed: 298

Interestingly, I'm not actually using the IoT library so removed it. Now I encounter compile issues:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp__CryptDecodeObjectEx@32 referenced in function _x509_schannel_create	<path>aziotsharedutil.lib(x509_schannel.obj)	1	
Error	LNK2019	unresolved external symbol __imp__CertCreateCertificateContext@12 referenced in function _x509_schannel_create	<path>aziotsharedutil.lib(x509_schannel.obj)	1	
Error	LNK2019	unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _x509_schannel_create	<path>aziotsharedutil.lib(x509_schannel.obj)	1	
Error	LNK2019	unresolved external symbol __imp__CertSetCertificateContextProperty@16 referenced in function _x509_schannel_create	<path>aziotsharedutil.lib(x509_schannel.obj)	1	
Error	LNK2019	unresolved external symbol __imp__CryptStringToBinaryA@28 referenced in function _x509_schannel_create	<path>aziotsharedutil.lib(x509_schannel.obj)	1

**Comment by PJ1980** [comment]
Note: Restoring to 1.0.28 without IoT libraries and the compile issues remain.

I'm using the uamqp library.

**Comment by PJ1980** [comment]
If I install Microsoft.Azure.IoTHub.AmqpTransport 1.1.8 and Microsoft.Azure.IoTHub.IoTHubClient 1.1.8 then it compiles ok again.

**Comment by mhshami01** [comment]
Hello @PJ1980,

Thank you for submitting this issue. To help us diagnose and fix the problem, it would be great if you can provide us with the following:

- sample code to reproduce the issue
- Windows version
- Visual Studio version

Sincerely,
-- Haitham

**Comment by tameraw** [comment]
@PJ1980 - Closing issue. Please let us know if you're still having issues and if you can provide us the information above.

**Comment by PJ1980** [comment]
Apologies for slow response. I hope the below assists, note it could totally be a case of PEBKAC...

Visual Studio 2017 on Windows 10 compiling using SDK 10.0.14393.0
NuGet packages:
* Microsoft.Azure.C.SharedUtility (v1.0.30) <- original report had 1.0.29
* Microsoft.Azure.uamqp (v1.0.30) <- original report had 1.0.29

As of today, issues are:
1) Cannot open include file: 'azure_uamqp_c/amqpalloc.h': No such file or directory	

2) Commenting out calls to methods in #1 above results in linker errors
1>aziotsharedutil.lib(x509_schannel.obj) : error LNK2019: unresolved external symbol __imp__CryptDecodeObjectEx@32 referenced in function _x509_schannel_create
1>aziotsharedutil.lib(x509_schannel.obj) : error LNK2019: unresolved external symbol __imp__CertCreateCertificateContext@12 referenced in function _x509_schannel_create
1>aziotsharedutil.lib(x509_schannel.obj) : error LNK2019: unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _x509_schannel_create
1>aziotsharedutil.lib(x509_schannel.obj) : error LNK2019: unresolved external symbol __imp__CertSetCertificateContextProperty@16 referenced in function _x509_schannel_create
1>aziotsharedutil.lib(x509_schannel.obj) : error LNK2019: unresolved external symbol __imp__CryptStringToBinaryA@28 referenced in function _x509_schannel_create

3) Noticing that it's looking for "aziot..." library I NuGet Microsoft.Azure.IoTHub.IoTHubClient (v1.1.10) and the compile now succeeds. And previously observed ReleaseSemaphore error is no longer experienced. 

... I guess it was PEBKAC.
