### ISSUE TITLE
socketio_berkeley: recv with MSG_NOSIGNAL causes errno 22 (EINVAL)

### ISSUE THREAD

**Issue by AndWass** [Azure/azure-c-shared-utility#605]
Version: 9e4322c9d88095ed276bf7e4b31b87b82b1c4d86 (used by [azure-iot-sdk-c LTS_07_2022_Ref02](https://github.com/Azure/azure-iot-sdk-c/tree/LTS_07_2022_Ref02))

System information:
Linux Yocto with kernel 3.18.140

Error output:
```
[error][azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c] [socketio_dowork:1068]: Socketio_Failure: Receiving data from endpoint: errno=22.
[error] IoT hub sdk: [azure-iot-sdk-c/umqtt/src/mqtt_client.c] [onOpenComplete:452]: Error: failure opening connection to endpoint
[info] IoT hub: connection status: result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason = IOTHUB_CLIENT_CONNECTION_NO_NETWORK
```

Manually patching the `recv` call to pass 0 as flags instead of `MSG_NOSIGNAL` does not yield the error above and communication is starting to work.

**Comment by danewalton** [comment]
Hi @AndWass 
I'll respond on the PR itself and we can discuss the scenario there.
