### ISSUE TITLE
tlsio_schannel memory leak

### ISSUE THREAD

**Issue by mhshami01** [Azure/azure-c-shared-utility#62]
The tlsio_schannel_destroy() function in src\tlsio_schannel.c does not free the x509certificate or the x509privatekey when they are set.

**Comment by anporumb** [comment]
Hello @mhshami01 ,

You will be looking at this in March (this month).

Best Regards,
Andrei Porumb

**Comment by mhshami01** [comment]
Hello @anporumb,

I have checked in the fix for this issue.

Best Regard,
--Haitham Shami
