### ISSUE TITLE
hard requirement on CURL 

### ISSUE THREAD

**Issue by Kevin0626** [Azure/azure-c-shared-utility#622]
Hi，

we have software using a previous version of c-utility and recently we want to update it to the latest version. Previously we turned off the option "use_http" to reduce the reliance on CURL and other components. 

After upgrading to the latest version, we found the option is no longer available. The following file has made it a must-have. .
https://github.com/Azure/azure-c-shared-utility/blob/master/configs/azure_c_shared_utilityConfig.cmake
```
if(UNIX)
    include(CMakeFindDependencyMacro)
    find_dependency(CURL)
endif()
```

@momuno, we found this change was introduced in your commitment below. We just wonder if it is possible to restore the "use_http" option. Our software runs on an embedded ARM system and currently has no need to use CURL. Thank you very much!

https://github.com/Azure/azure-c-shared-utility/commit/73a2039cc0de5ececf5755ebe731a6b5b98f85da

**Comment by ewertons** [comment]
Issue fixed. If you would like to follow up please reopen it.
Thank you for your contribution.
-Azure SDKs Team.
