### ISSUE TITLE
openSSL 1.1.1n handhshake returning error code 2

### ISSUE THREAD

**Issue by venugchary** [Azure/azure-c-shared-utility#648]
I am using OpenSSL 1.1.1n version with Azure C SDK and facing below error code 2 while handshaking with iothub end point. Looks like below code inside adaptor/tlsio_openssl.c is not handled for Error Code 2 (SSL_ERROR_WANT_READ). Can you help how to handle this please?

// Non-NULL tls_io_instance is guaranteed by callers.
// We are in TLSIO_STATE_IN_HANDSHAKE when entering this method.
static void send_handshake_bytes(TLS_IO_INSTANCE* tls_io_instance)
{
    int hsret;
    // ERR_clear_error must be called before any call that might set an
    // SSL_get_error result
    ERR_clear_error();
    hsret = SSL_do_handshake(tls_io_instance->ssl);
    if (hsret != SSL_DO_HANDSHAKE_SUCCESS)
    {

**Comment by venugchary** [comment]
Any inputs are really appriciated.

**Comment by RLeclair** [comment]
Hi @venugchary, we are looking into the issue at the moment, we appreciate your patience

**Comment by RLeclair** [comment]
Hi @venugchary, what error message are you seeing? Can you provide logs?

**Comment by RLeclair** [comment]
We will close this issue as it has not been updated in a while. Please feel free to reopen it or open a new one if you would like to follow up. 
Thanks, 
Azure IoT SDKs Team
