### ISSUE TITLE
CA for mbed tls authentication

### ISSUE THREAD

**Issue by SummerSun** [Azure/azure-c-shared-utility#67]
Trying the tls io in mbed os 5 with a mxchip.

Met an error "got no CA chain' when creating tls io.
In mbed-os code, the logic is like this:
```
if( authmode != MBEDTLS_SSL_VERIFY_NONE )
    {
        mbedtls_x509_crt *ca_chain;
        mbedtls_x509_crl *ca_crl;

#if defined(MBEDTLS_SSL_SERVER_NAME_INDICATION)
        if( ssl->handshake->sni_ca_chain != NULL )
        {
            ca_chain = ssl->handshake->sni_ca_chain;
            ca_crl   = ssl->handshake->sni_ca_crl;
        }
        else
#endif
        {
            ca_chain = ssl->conf->ca_chain;
            ca_crl   = ssl->conf->ca_crl;
        }

        if( ca_chain == NULL )
        {
            MBEDTLS_SSL_DEBUG_MSG( 1, ( "got no CA chain" ) );
            return( MBEDTLS_ERR_SSL_CA_CHAIN_REQUIRED );
        }
```
But when i checked the code, correct me if i am wrong, I find that during creation, io_create_parameters contains only host name and port, seems there is no way to providing ca chain:
```
CONCRETE_IO_HANDLE tlsio_mbedtls_create(void* io_create_parameters)
  -> mbedtls_init((void *)result,tls_io_config->hostname);
     -> mbedtls_x509_crt_init(&result->cacert)
          mbedtls_ssl_conf_authmode(&result->config,MBEDTLS_SSL_VERIFY_OPTIONAL)
```

Update the auth mode to NONE then it works, but I got no clue if it is OPTIONAL.

Appreciate any help here.

**Comment by SummerSun** [comment]
I tried xio_setoption:
```
XIO_HANDLE tlsio = (XIO_HANDLE)context;
xio_setoption(tlsio, "TrustedCerts", certificates);
```
Same error.

**Comment by ewertons** [comment]
Hi @SummerSun , we will be investigating this issue soon.

Thanks for reporting it.

**Comment by tameraw** [comment]
@SummerSun - Is this still an issue for you? Also, the authmode should be set to MBEDTLS_SSL_VERIFY_REQUIRED.

**Comment by SummerSun** [comment]
@tameraw - Hi, thanks for asking. The issue is still there for me. Have to set to OPTIONAL to workaround it. ewertons said would be investigating the issue, not sure if there's any find?

**Comment by JetstreamRoySprowl** [comment]
@SummerSun - I was able to successfully run the tlsio_mbed on an ESP32 using MBEDTLS_SSL_VERIFY_REQUIRED by setting the "TrustedCerts" option with the certs defined [here:](https://github.com/Azure/azure-iot-sdk-c/blob/master/certs/certs.c.) If you look at the Azure IoT mqtt [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c) and make sure  MBED_BUILD_TIMESTAMP is defined you'll see how and when the cert needs to be set to make it work properly.

**Comment by SummerSun** [comment]
I made it to set the trusted certificates and https request and I will give it a try again.
