### ISSUE TITLE
Multiple definitions of Base64_Encode() when WolfSSL is used.

### ISSUE THREAD

**Issue by ArsalanSaleemGhuman** [Azure/azure-c-shared-utility#68]
# PROBLEM:
The file [base64.c](https://github.com/Azure/azure-c-shared-utility/blob/6055dd31843aef0412355c234ce3af6d81690629/src/base64.c) in the c-utility shared repo defines the function Base64_Encode().

The same function is also defined by WolfSSL in the file [coding.c](https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/coding.c)

When the azure c-iot-sdk is compiled using WolfSSL an error occurs related to multiple definitions of the Base64_Encode() function.

To reproduce it you can simply use WolfSSL and ensure that WOLFSSL_BASE64_ENCODE is defined. 

In my case Nucleus was the OS but i am sure it can be reporduced on any platform such as LINUX or WINDOWS

# FIX:
To Fix the issue i changed the name in the following files of the SDK:
## c-utility/inc/azure_c_shared_utility/base64.h : 
old name : Base64_Encode
new name : Base64_Encode_Azure

## c-utility/src/base64.c : 
old name : Base64_Encode()
new name : Base64_Encode_Azure()

## c-utility/src/sastoken.c : 
old name : Base64_Encode()
new name : Base64_Encode_Azure()

**Comment by anhashia** [comment]
Hi @ArsalanSaleemGhuman 
I had chance to look at this. Yeah, it can be an issue if you try to build WOLF SSL with  **WOLFSSL_BASE64_ENCODE** define. But I was also able to build WOLF SSL on Windows **without** this define. 

Is there any reason that you want to use WOLFSSL_BASE64_ENCODE  with WOLF SSL and not use implementation in azure_c_shared_utility while using Azure IoT C SDK  ? Trying to understand the use case here.

For your reference, currently C SDK does have **TI RTOS CC3200** using WOLF SSL as a supported configuration.
https://github.com/Azure/azure-iot-sdk-c/blob/master/build_all/tirtos/Makefile#L36

**Comment by ArsalanSaleemGhuman** [comment]
This problem doesn't occur in the default build of Nucleus RTOS with Azure. But in a more advanced configuration, the problem may occur because some Nucleus RTOS components rely on the WolfSSL library, so the library would be included in the build in such cases. So it would be a nice-to-have item to fix this naming conflict, if easily possible.

**Comment by anhashia** [comment]
Fix checked in https://github.com/Azure/azure-c-shared-utility/commit/11f504af8606dde58eae3337f4b3a517e7fa878d
