### ISSUE TITLE
Base64_Encoder

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-c-shared-utility#73]
Hi dear friends,

Recently there was a rename from Base64_Encode to Base64_Encoder.
This is just poetry and you might decide to fix this at your convenience, but Base64_Encoder is not a good name (consistent with how naming is done throughout the C SDK).

Usually the naming is {namespace}_{verb}
Like String_create.

Base64_Encoder refers to the noun encoder, does not end with a verb. If this function would have created an encoder it could be called Base64_Encoder_Create. But the function *encodes* bytes to Base64, thus it could be called something like `Base64_Encode_Bytes`.

This is obviously a small issue, but since the fix for the name collision is being done now, I'd suggest doing the rename now, so that it does not get dragged forever as some minor annoyance.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
Sure, I guess I have until 2021 to fix it based on the above timeline :-).

**Comment by az-iot-builder-01** [comment]
@massand, @dcristoloveanu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
