### ISSUE TITLE
Add WolfSSL as a submodule

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-c-shared-utility#74]
In order to have an easier handling of WolfSSL I suggest adding it as a submodule.
Thoughts?

Cheers,
/Dan

**Comment by ewertons** [comment]
It could be a good idea if it makes integration with c-shared easier.
What are the issues of using it as an external module?

**Comment by dcristoloveanu** [comment]
The drawback of adding as a submodule is the fact it would get cloned even if not used.
On the other hand, the pro is when it is used, there would be no need for WolfSSLDir and other integration artifacts.
Ideally it should be just adding to the CMakeLists another subdirectory. If WolfSSL does not currently have a CMakeLists it should be fairly easy to put one together and even contribute it.

Cheers,
/Dan

**Comment by tameraw** [comment]
@dcristoloveanu - Currently not planning to add this into a submodule.
