### ISSUE TITLE
 FIPS_MODE_DISABLE flag

### ISSUE THREAD

**Issue by michaelinipop** [Azure/azure-c-shared-utility#83]
I have been working hard to cross compile this library for our own custom target deployment, however I have been running into a great deal of trouble with OpenSSL with FIPS support. I can't get my SSL build to pass the key verification process. As I am a supporter of good security practices , this level of protection for our application is kind of overkill.  Therefore I was wondering if an FIPS_MODE_DISABLE flag can be added to the  tlsio_openssl.c file around  line 1017    

`#if (OPENSSL_VERSION_NUMBER >= 0x00907000L) && (OPENSSL_VERSION_NUMBER < 0x20000000L)
#ifndef   FIPS_MODE_DISABLE
 FIPS_mode_set(0);
#endif
#endif` 

Any thoughts ?

**Comment by massand** [comment]
There hasn't been any other requests for this issue.

**Comment by az-iot-builder-01** [comment]
@michaelinipop, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
