### ISSUE TITLE
Why is the state not changed in the tlsio_mbedtls on_underlying_io_close_complete()

### ISSUE THREAD

**Issue by Resultfactory** [Azure/azure-c-shared-utility#84]
Hi,

We are using part of this utility in combination with a ESP32 chip.
We are seeing xio dowork calls after our connection has closed.
An error occurred and the state was changed to TLSIO_STATE_ERROR, the connection was being closed and after some debugging we found that the state in tlsio_mbedtls was not changed to TLSIO_STATE_NOT_OPEN, and remains in TLSIO_STATE_CLOSING state.
Which allows the dowork in tlsio_mbedtls to try and do actual work.

On line 236 and 237 we saw commented lines that would fix this problem
[on_underlying_io_close_complete()](https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/tlsio_mbedtls.c#L236)

Nowhere else but the create and open functions is the state changed to TLSIO_STATE_NOT_OPEN.

Are there any reasons why these lines are commented?

**Comment by JetstreamRoySprowl** [comment]
We've got a fix identified for this one, and are moving it through the checkin process now.

**Comment by JetstreamRoySprowl** [comment]
The fix has been checked in to master, and will appear in the next release.

**Comment by Resultfactory** [comment]
Thanks, I see it has made it's way into master 2743fead5c2dcf6852bee59c4e6b7ec83fba6855
