### ISSUE TITLE
no tlsio error callback when TLS session is rejected by peer

### ISSUE THREAD

**Issue by szsobocinski** [Azure/azure-c-shared-utility#85]
I'm running the recent version of c-utlity (62223f1) on a Linux host with OpenSSL 1.0.2g.

The issue is easily reproducible in scenarios where tlsio's connection is refused, e.g.:
- tlsio uses TLSv1, but the peer requires TLSv1.2;
- the peer's certificate is not signed by CA known to tlsio client.

In such cases I can observe TLS alert packets and actually whole TCP session shutting down, but neither on_io_error nor on_io_open_complete (expected IO_OPEN_ERROR as result parameter) callback is executed.

**Comment by tameraw** [comment]
@szsobocinski - Thanks for filing this issue. We'll look into it.

**Comment by JetstreamRoySprowl** [comment]
@szsobocinski - thanks for the clear report. We've got a fix for this one checked in to the latest master: https://github.com/Azure/azure-c-shared-utility/blob/master/src/tlsio_openssl.c

**Comment by szsobocinski** [comment]
@JetstreamRoySprowl I can confirm it works now, thanks!
