### ISSUE TITLE
ESP32 Component's makefile missing a dependency

### ISSUE THREAD

**Issue by manux54** [Azure/azure-c-shared-utility#94]
Azure IoT builds are failing on the ESP32 Toolchain.  A dependency to __iothub_client_retry_control__ has been added in __iothubtransport_mqtt_common.c__: Azure/azure-iot-sdk-c@3e95cee02e4dff480ceb46171f3a085a4cc7d437 but the component object
`sdk/iothub_client/src/iothub_client_retry_control.o \`
is missing from the component's makefile (_azure-c-shared-utility/build_all/esp32/sdk/component.mk_).
This produces errors such as 
`libazure-iot.a(iothubtransport_mqtt_common.o):(.literal.InitializeTransportHandleData+0x40): undefined reference to retry_control_create`
Adding `sdk/iothub_client/src/iothub_client_retry_control.o \` to `azure-c-shared-utility/build_all/esp32/sdk/component.mk` under `COMPONENT_OBJS` fixes the issue.

**Comment by JetstreamRoySprowl** [comment]
@manux54 - thank you for the excellent report and analysis. I've checked this fix into the current [c-utility master](https://github.com/Azure/azure-c-shared-utility/blob/4f196f30675bd4c3f448d89b0efc8e19e23be1c9/build_all/esp32/sdk/component.mk#L59).

**Comment by JetstreamRoySprowl** [comment]
This has been fixed since August. Note that Azure IoT's ESP32 support has been moved [here](https://github.com/Azure/azure-iot-pal-esp32)
