### ISSUE TITLE
installation steps are broken

### ISSUE THREAD

**Issue by nayato** [Azure/azure-c-shared-utility#98]
Running `cmake -Duse_installed_dependencies=ON ../` I get this:
```
CMake Error at CMakeLists.txt:659 (install):
  install TARGETS given target "aziotsharedutil_dll" which does not exist in
  this directory.
```
Dan advised to add `-Dbuild_as_dynamic=ON` and it worked. He also suggested that dll was supposed to be built always.

**Comment by markrad** [comment]
I have a pull request waiting that will address this issue.

**Comment by markrad** [comment]
Hi @nayato, 

This fix has been integrated into master.

_Mark Radbourne MSFT_
